### ISSUE TITLE
Отображается 2 индикатора громкости: MacOS и от монитора LG

### ISSUE THREAD

**Issue by slepoy1** [juvirez/yandex-music-app#100]
Здравствуйте. Монитор LG 27UK850-W и MacOS 12.1 (21C52) [но проблема была актуальна также для версий 10 и 11].
При использовании клавиш громкости (либо ползунка громкости приложения), помимо индикатора громкости MacOS, дополнительно отображается индикатор громкости монитора LG (черный на скриншоте).

Включение чекбокса "OSD scale: Use fine OSD scale for volume" (что бы это ни значило) не решает проблему.

Ожидаемый результат: отображать только индикатор громкости MacOS. Это возможно?

Спасибо.

![](https://i.ibb.co/5kqwvy0/FDEEF0-CC-F336-4-CA4-875-E-5377061-DC862.jpg)
![](https://i.ibb.co/Xx9CN0J/2022-01-10-22-07-32.png)
![](https://i.ibb.co/LgKqj8y/2022-01-10-22-07-18-1.png)
![](https://i.ibb.co/m98RBp7/2022-01-10-22-06-02.png)
![](https://i.ibb.co/gMcQXWN/2022-01-10-22-05-55.png)

**Comment by HansCraftsman** [comment]
Тот момент когда ник говорит о многом)
Вы не в том репозитории) Что это за программа?

**Comment by slepoy1** [comment]
> Что это за программа?
Yandex Music App.
Яндекс Музыка для MacOS.

**Comment by iswitch** [comment]
Вам наверно в этот репозиторий
https://github.com/MonitorControl/MonitorControl

**Comment by HansCraftsman** [comment]
> Яндекс Музыка для MacOS.

А причем тут ваш монитор и клавиши громкости? Это приложение на регулировку громкости не влияет, возможно вам поможет программа [https://rogueamoeba.com/soundsource/](SoundSource)
Там есть настройка управления общей громкостью устройств
![image](https://user-images.githubusercontent.com/94063665/149365919-e3ba8fb8-5cb9-4032-b9b6-3b87b3de982a.png)
