### ISSUE TITLE
Новая версия

### ISSUE THREAD

**Issue by romant094** [juvirez/yandex-music-app#102]
Сегодня пришло письмо с оповещением о новой версии. Перехожу по ссылке из него, но там 404. Как скачать?

https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.0

**Comment by realabs** [comment]
The same

**Comment by juvirez** [comment]
Сорян, случайно опубликовал раньше времени :)
Но теперь ссылка должна работать.
