### ISSUE TITLE
Баг с Global Hotkeys (1.6.0)

### ISSUE THREAD

**Issue by iswitch** [juvirez/yandex-music-app#103]
При нажатии в меню на Global Hotkeys (разрешения дал) появляется пустое окно.
<img alt="Global Hotkeys" src="https://user-images.githubusercontent.com/124419/150702445-3f61f254-2fe1-4736-82d2-125c6c56c17a.png">

**Comment by HansCraftsman** [comment]
+ На обеих версиях (intel и arm), на интеловской версии еще заметил, что если переименовать приложение в папке Applications (убрать слово unofficial), то права доступа не сохраняются и он снова просит их разрешить и сбрасывает галку в настройках универсального доступа (BigSure)

**Comment by homm** [comment]
У меня вообще ничего не открывается при выборе Global Hotkeys, каждый раз говорит дать привилегии, хотя всё естественно дано. MacOS 10.14 Mojave

**Comment by homm** [comment]
> если переименовать приложение в папке Applications (убрать слово unofficial),

Кстати, делаю это первым делом всегда. В прошлой версии все нормально работало

**Comment by homm** [comment]
> получается, выдать права никак не возможно после переименования приложения?

Всё верно. До переименования всё работает, после переименования при выборе меню Global Hotkeys каждый раз появляется этот диалог:

<img width="456" alt="Screenshot 2022-02-08 at 12 19 59" src="https://user-images.githubusercontent.com/128982/152956734-e42f311a-00ae-41bc-ac23-6e6c1606c238.png">
 

В предыдущей версии работает с любым названием приложения, хотя в списке приложений имя не меняется:
<img width="363" alt="Screenshot 2022-02-08 at 12 23 43" src="https://user-images.githubusercontent.com/128982/152957085-c9213ffb-3eca-475c-8984-746d96e8940b.png">

**Comment by juvirez** [comment]
>В предыдущей версии работает с любым названием приложения, хотя в списке приложений имя не меняется:

На скриншоте старая версия приложения. В новой версии другая иконка и название без скобок. Возможно, новое приложение нужно добавить через плюсик, если его нет в списке.

**Comment by homm** [comment]
> На скриншоте старая версия приложения.

Всё верно, я так и написал. Старая версия работает с любым именем приложения, а в списке «каноничное» имя. Новая версия тоже была в списке, но к моменту когда я делал скриншот я её уже снёс.
