### ISSUE TITLE
Приложение не дает ноутбуку спать, даже если музыка не воспроизводится

### ISSUE THREAD

**Issue by SpiderMorion** [juvirez/yandex-music-app#104]
После обновления обратил внимание, что ноут не спит, хотя стоит без дела уже более суток. Полез в мониторинг, а там такое:
![image](https://user-images.githubusercontent.com/98449582/151120399-d513b1bf-71c5-4872-a094-b354094eb240.png)

Было бы неплохо сделать так, чтобы приложение блокировало сон только при воспроизведении музыки.

**Comment by juvirez** [comment]
fixed: https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.1
