### ISSUE TITLE
Клик на уведомление не отображает приложение

### ISSUE THREAD

**Issue by iswitch** [juvirez/yandex-music-app#105]
Было бы здорово, если по клику на уведомление, открывалось окно приложения. Сейчас при клике у приложения появляется фокус, но оно не разворачивается из дока.

**Comment by juvirez** [comment]
[Released](https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.2)

**Comment by roman2p0** [comment]
плюсую! есть проблема, жду обновления)

**Comment by juvirez** [comment]
@roman2p0 фикс уже вышел в версии 1.6.2: https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.2

**Comment by Gremt** [comment]
Приложение супер, огонь! Можно добавить функцию для прослушивания на другом сетевом муз устройстве? Очень не хватает. Такая функция есть в мобильном приложении на андроид, буду очень благодарен.
