### ISSUE TITLE
Очистка памяти

### ISSUE THREAD

**Issue by xDarkOne** [juvirez/yandex-music-app#108]
Хотел уточнить - присутствует ли в приложении функция очистки памяти?
Т.к. мне кажется, что до перезапуска кэшируется вообще всё.
Было бы здорово, чтобы присутствовал какой-нибудь лимит.
![image](https://user-images.githubusercontent.com/20536183/154694684-e39c8b2c-1eca-451d-b686-919b9f7c4f55.png)

**Comment by ivan-gaydamakin** [comment]
<img width="560" alt="Screenshot 2022-03-03 at 11 42 44" src="https://user-images.githubusercontent.com/84778353/156539370-8a9be3d6-eb44-4aaf-a8af-d29aafa6ab91.png">
неделю аппка поработала, нормально так выжрала))

**Comment by romant094** [comment]
![image](https://user-images.githubusercontent.com/37865987/156539862-487d8a81-ec44-4de2-864e-f1eb3b7a23e4.png)

**Comment by romant094** [comment]
В какой версии нет утечки?

**Comment by ivan-gaydamakin** [comment]
> В какой версии нет утечки? И когда планируется устранение?

Version 1.5.1 (1.5.1)

**Comment by juvirez** [comment]
>Думал, что поборол эту утечку, но как оказалось ещё нет.

Всё таки фикс чистки памяти работает, но не попал в сборку релиза.
Пересобрал, теперь вроде ок: [v1.6.2](https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.2)
