### ISSUE TITLE
Приложение критует, если нет интернета

### ISSUE THREAD

**Issue by EvgenyLi** [juvirez/yandex-music-app#110]

**Comment by VanishMax** [comment]
Такая же проблема

**Comment by jkttim** [comment]
Да, есть такое. Вылетает при переключение между сетями.

**Comment by juvirez** [comment]
Фикс в релизе 1.6.3: https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.3

**Comment by jkttim** [comment]
> Фикс в релизе 1.6.3: https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.3

благодарю :)

**Comment by jkttim** [comment]
> Фикс в релизе 1.6.3: https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.3

Нет цифровой подписи в релизе :(

**Comment by juvirez** [comment]
>Нет цифровой подписи в релизе :(

ой, пересоздал релиз

**Comment by saltukkos** [comment]
@juvirez Сейчас приложение не фаталится, но если были проблемы с интернетом, UI зависает, приложение не реалигурет на кнопки, даже свернуть его нельзя. Причём музыка в фоне играет и треки даже переключаются после того, как предыдущая песня закончится. https://www.youtube.com/watch?v=TlspP6WonGo
