### ISSUE TITLE
[Feature] Homebrew

### ISSUE THREAD

**Issue by drezo** [juvirez/yandex-music-app#112]
В первую очередь поблагодарю разработчика!

Спасибо за предоставленное решение 🚀

По возможности - опубликуйтесь в Homebrew Cask ([https://brew.sh/](url))

`$ brew install --cask yandex-music-app`

Спасибо!

**Comment by juvirez** [comment]
Готово: https://github.com/Homebrew/homebrew-cask/pull/122562

Только название пришлось использовать немного другое:
`brew install --cask yandex-music-unofficial`
