### ISSUE TITLE
JavaScript error

### ISSUE THREAD

**Issue by LoveBloodAndDiamonds** [juvirez/yandex-music-app#116]
Привет, пользуюсь вашим приложением каждый день! Большое спасибо, все круто, и шорткаты, и сплит-скрин, но я столкнулся с очень противной пробелмой:
Когда загружаешь на ЯМ свою музыку, как например я сделал с новым альбомом КУОКа, то при его воспроизведении через приложение выходить ошибка 
В браузере и на айфоне такой ошибки нет, прикрепляю скрин
![image](https://user-images.githubusercontent.com/95250856/158360362-44be5448-d1a7-4f66-9134-f6b5526caa59.jpeg)

**Comment by juvirez** [comment]
@LoveBloodAndDiamonds Привет, больше не воспроизводится? Вроде это давным давно было исправлено.
