### ISSUE TITLE
Темный режим в приложении

### ISSUE THREAD

**Issue by ivanlarionov1977** [juvirez/yandex-music-app#117]
Здравствуйте! Не нашел как включить темный режим в приложении. По умолчанию в системе темный режим. приложение в первый раз и далее запускается в светлой теме. Подскажите, пожалуйста, как включить темную тему в приложении?

**Comment by juvirez** [comment]
Здравствуйте!
Автоматического переключения между темами пока нет, но это есть в планах.

А пока тёмную тему можно включить через интерфейс яндекс музыки:
![image](https://user-images.githubusercontent.com/1862143/158529861-4c824f5d-bae5-4256-bcba-4d1b6496505d.png)

**Comment by ivanlarionov1977** [comment]
Спасибо большо! Вы молодцы!
