### ISSUE TITLE
Чем дольше включено, тем больше памяти жрет

### ISSUE THREAD

**Issue by Rezzh** [juvirez/yandex-music-app#118]
Мак мини на м1 на 8гб и 256гб.
Сначала все норм, но после нескольких часов уже жрет под 6-8гб. Это жеска

**Comment by juvirez** [comment]
Попробуй последнюю версию приложения: https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.2
Там как раз решали эту проблему.

**Comment by juvirez** [comment]
🤔 У меня тоже запущена 1.6.2 с момента релиза и почти весь день играет музыка.
По всем процессам приложения кушает в сумме ~350МБ.

@romant094 Правильнее смотреть все процессы приложения. В прошлый раз память утекала из процесса `Yandex Music Unofficial Helper (Renderer)`. Можно вбить в поиск "Yandex Music", чтобы отобразить все процессы.

@Volosatiyslon Чтобы я мог это поисследовать, мне нужен sample (и возможно spindump) процесса, который ест память больше всего:

<img width="567" alt="image" src="https://user-images.githubusercontent.com/1862143/158871201-fbe95774-4c69-4726-be3e-6eadf83f0350.png">

**Comment by Rezzh** [comment]
1.6.2 норм

**Comment by Volosatiyslon** [comment]
ситуация через 2 дня 
<img width="993" alt="Screenshot 2022-04-08 at 22 05 34" src="https://user-images.githubusercontent.com/47186157/162508346-44097ce0-bf2e-4424-9483-6b824fe9c1f1.png">
[Sample of Yandex Music Unofficial Helper (Renderer).txt](https://github.com/juvirez/yandex-music-app/files/8454620/Sample.of.Yandex.Music.Unofficial.Helper.Renderer.txt)
[spindump of Yandex Music Unofficial Helper (Renderer).txt](https://github.com/juvirez/yandex-music-app/files/8454621/spindump.of.Yandex.Music.Unofficial.Helper.Renderer.txt)
файлы приложил
