### ISSUE TITLE
Приложение не позволяет заснуть Mac когда не проигрывается музыка.

### ISSUE THREAD

**Issue by sergeyklochko** [juvirez/yandex-music-app#120]
В отличии от всех остальных плееров, и даже завернутой в оболочку версии сайта, приложение не позволяет уснуть компьютеру и даже отключить экран во время простоя. Это можно исправить?

<img width="852" alt="image" src="https://user-images.githubusercontent.com/37343789/160273692-3c004dbd-2167-42e5-b91c-640c0d876a94.png">

**Comment by 9en9i** [comment]
Заметил, что переключается в зависимости от того включена ли музыка или нет. Думаю это весьма логичное и ожидаемое поведение

**Comment by sergeyklochko** [comment]
В том-то и дело, что у меня не переключается по какой-то причине. может быть потому что есть второй монитор и player на нем.

**Comment by sergeyklochko** [comment]
Ни через минуту, ни через пять. Этот скриншот вообще после запуска и ничего никуда не играло минут десять. То есть с момента запуска, до момента скриншота прошло минут десять и при этом ничего не играло вообще в этот промежуток времени.

**Comment by juvirez** [comment]
Привет! Поисследовал проблему, вот что могу сказать:
* код приложения, управляющий предотвращением засыпания тут никак не задействован
* тут сама OS считает, что засыпать не стоит, если это приложение отображается
* причём, если загородить приложение другим окном, preventing sleep переключается в No
* воспроизводится только на главной странице Яндекс Музыка

Система сама решает не засыпать при отображении главной страницы Яндекс Музыки, потому что на главной странице воспроизводится анимация "Моя волна", которая по сути является зацикленным воспроизведением mp4 файла.
Если отображение этой анимации скрыть — preventing sleep переключается в No, даже если приложение находится в фокусе.

У меня есть большое желание убрать это видео всем. Помимо предотвращения засыпания, оно ещё и кушает CPU/GPU.
Ещё вариант: приостанавливать воспроизведения видео при потере фокуса. И можно вовсе не показывать видео, если "Моя волна" не воспроизводится. Пока склоняюсь к этому варианту.

**Comment by sergeyklochko** [comment]
> У меня есть большое желание убрать это видео всем. Помимо предотвращения засыпания, оно ещё и кушает CPU/GPU. Ещё вариант: приостанавливать воспроизведения видео при потере фокуса. И можно вовсе не показывать видео, если "Моя волна" не воспроизводится. Пока склоняюсь к этому варианту.

Абсолютно адекватное желание. эта анимация там абсолютно неуместна ни стилистически, ни функционально. я не буду страдать, если ее не будет совсем. допускаю, что у большинства пользователей она тоже не вызывает какой-то привязанности.

**Comment by romant094** [comment]
Может стоит дать пользователям выбор, добавив флаг "Показать анимацию"?)

**Comment by juvirez** [comment]
Скрыл видео полностью в релизе 1.6.3: https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.3

>Может стоит дать пользователям выбор, добавив флаг "Показать анимацию"?)

Тоглера в настройках не делал. Но возможность вернуть анимацию есть.
Для этого нужно открыть файл `~/Library/Application\ Support/yandex-music-app/config.json` и добавить строчку `"animations_disabled": false`
