### ISSUE TITLE
Добавить поддержку ссылок на треки/плейлисты/альбомы в Яндекс Музыке

### ISSUE THREAD

**Issue by flaksp** [juvirez/yandex-music-app#122]
Очень хотелось бы увидеть поддержку приложением ссылок на Яндекс.Музыку. Например, если в каком-то мессенджере прислали ссылку на трек, чтобы она открылась не в браузере, а в приложении.

Скорее всего перехват нажатий на ссылки не получится сделать штатными средствами, для этой цели существуют специализированные приложения, одним из самых популярных является [Choosy](https://www.choosyosx.com).

Как это работает: Choosy устанавливается в MacOS как браузер по умолчанию, в настройках программы можно выставлять правила перенаправления ссылок в конкретные приложения:

<img width="640" alt="Screenshot 2022-03-30 at 21 46 59" src="https://user-images.githubusercontent.com/12474739/160908724-b30a5e2c-c03a-4c4b-8eb9-dbb155aab03c.png">

Очень удобно было открывать таким образом ссылки на Spotify прямо в клиенте на маке.

Если настроить Choosy аналогично для данного приложения Яндекс Музыки, то оно не работает:

<img width="1400" alt="Screenshot 2022-03-30 at 21 49 28" src="https://user-images.githubusercontent.com/12474739/160909079-3621c224-68ed-4149-9a22-673302778369.png">

При этом в приложении есть поддержка открытия ссылок, но через меню-бар:

<img width="1491" alt="Screenshot 2022-03-30 at 21 53 47" src="https://user-images.githubusercontent.com/12474739/160909693-99a927d4-e7f1-40d7-a59f-51990dfa0f17.png">

В общем было бы очень удобно, если бы приложение корректно кушало ссылки. Вижу похожий по идее PR #92, но он предлагает использование кастомной схемы, что для приложений типа Choosy не подходит (т.к. они не трансформируют ссылки).

**Comment by CheeryLee** [comment]
Похоже, здесь проблема спрятана несколько глубже. Такие приложения могут самостоятельно преобразовывать ссылки, чтобы как раз использовать deep link. То есть, например, на выходе получим не 
https://open.spotify.com/track/5eGeIWhWdLFlbCiuROoFwD?si=c718047ab6f74d68 , а что-то вроде `spotify:track:5eGeIWhWdLFlbCiuROoFwD?si=f85ca08d6a8e47b3`

Как раз есть примерный реф из похожего приложения: https://github.com/will-stone/browserosaurus/blob/main/src/config/apps.ts

Сам Spotify может подтягивать ссылку из аргумента при запуске. В теории такой функционал довольно легко реализовать и здесь, но вот он не будет работать с Choosy.
Если я сделаю `open -n /Applications/Yandex\ Music\ Unofficial.app https://music.yandex.ru/album/20812263/track/99563934`, то получится то, что вы хотите. Однако Choosy об этом не узнает.

**Comment by fixrom** [comment]
Да, было бы очень удобно. Сделайте плиз))

Когда кто-либо присылает ссылку на Яндекс.Музыку приходится — копировать ссылку > открывать приложение >  вставлять туда ссылку и только потом уже слушать...

**Comment by HansCraftsman** [comment]
> Когда кто-либо присылает ссылку на Яндекс.Музыку приходится — копировать ссылку > открывать приложение > вставлять туда ссылку и только потом уже слушать...

Пока не завезли эту фичу - рекомендую установить это расширение, оно перенаправит ссылки с браузера сразу в приложения, костыль, но все равно удобнее чем руками)
https://chrome.google.com/webstore/detail/open-yandex-music-macos-a/afcbcmeeninkbbibemgngnendopcpedb

**Comment by fixrom** [comment]
Я пользуюсь Safari

**Comment by CheeryLee** [comment]
Как вариант, есть еще нативный способ реализации:
https://developer.apple.com/documentation/xcode/supporting-associated-domains

Тогда можно будет перехватить music.yandex.ru. Здесь потребуется аккаунт разраба.

**Comment by juvirez** [comment]
Приложение теперь поддерживает открытие ссылок через Choosy и другие подобные программы.
Исправлено в [v1.8.0](https://github.com/juvirez/yandex-music-app/releases/tag/v1.8.0)
