### ISSUE TITLE
Не отображается интерфейс приложения на макбуке

### ISSUE THREAD

**Issue by Ilaadfdsa** [juvirez/yandex-music-app#124]
При открытии приложения не отображается интерфейс, пофиксите

**Comment by dkuzmenchuk** [comment]
@Ilaadfdsa У меня такое было, когда случайно переместил окно за пределы экрана. Исправляется Window -> Zoom в статус баре

**Comment by Ilaadfdsa** [comment]
> @Ilaadfdsa У меня такое было, когда случайно переместил окно за пределы экрана. Исправляется Window -> Zoom в статус баре

Спасибо, помогло

**Comment by juvirez** [comment]
Фикс в релизе: https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.3
