### ISSUE TITLE
Название альбома в уведомлении

### ISSUE THREAD

**Issue by dikrik** [juvirez/yandex-music-app#125]
Здравствуйте. Сейчас нотификации приходят следующим образом.

<img width="343" alt="Now" src="https://user-images.githubusercontent.com/21036080/161437754-26c4a07c-abfd-4987-83fe-80cc669a711e.png">

Обратил внимание, что есть пустая строчка внизу, которая не используется. Если это возможно, то было бы круто там отобразить какую-то дополнительную информацию о треке. Для примера, это могло бы быть название альбома, который сейчас начал играть. Может быть что-то другое. Спасибо.

<img width="343" alt="Test" src="https://user-images.githubusercontent.com/21036080/161437829-e4b48c34-218a-4b77-8d66-851da8a3f6da.png">

И хотел бы поблагодарить за приложение. Очень выручает 💪

**Comment by juvirez** [comment]
Здравствуйте.
Думаю, лучше сделать не третей строчкой, а во второй через дефис, как это делает Apple Music:
<img width="370" alt="image" src="https://user-images.githubusercontent.com/1862143/162585328-ae4e8748-eb71-4b3a-9d07-425b64359cf5.png">

**Comment by CheeryLee** [comment]
Поддерживаю @juvirez и предлагаю код: https://github.com/juvirez/yandex-music-app/pull/144 

![Image 2022-05-15 15-53-29](https://user-images.githubusercontent.com/11297752/168474081-232e21d8-4cbe-4014-b3fc-852d4f77c502.png)

![Снимок экрана 2022-05-15 в 15 53 45](https://user-images.githubusercontent.com/11297752/168474089-02439ae4-3ada-4fb4-aa9e-1aae330335a2.png)

**Comment by juvirez** [comment]
Released: [v1.7.0](https://github.com/juvirez/yandex-music-app/releases/tag/v1.7.0)
