### ISSUE TITLE
Ухудшается качество вопросизведения, когда появляется еще один источник звука

### ISSUE THREAD

**Issue by staticcole** [juvirez/yandex-music-app#126]
Всем привет

При прослушивании музыки и переходе в условный Google Meet, происходит лаг звука на одну секунду и он начинает хрипеть, как будто музыка играет через телефонную трубку. Как только выхожу из мита — опять лаг в секунду и звук возвращается к норме.

macOS 12.3 (21E230)
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
2,3 GHz Dual-Core Intel Core i5
8 GB 2133 MHz LPDDR3

**Comment by juvirez** [comment]
Привет!
Наверно ты используешь беспроводную гарнитуру? И в meet используется микрофон этих наушников?
https://support.apple.com/ru-ru/HT208896

**Comment by staticcole** [comment]
Точно, оно. Сори, не разобрался в матчасти. Спасибо большое!
