### ISSUE TITLE
[bug][new idea]Работает только как браузер. Нет функционала приложения

### ISSUE THREAD

**Issue by vasnikolv** [juvirez/yandex-music-app#130]
Спасибо за приложение! Пока не платежеспособен(аккаунт дарит брат со своей работы), вот вырасту и задоначу)

Ставил разные хоткеи, не заметив поставил на mute и "паузу/воспроизведение" сочетание "ctr + alt + m". Тыкнул сохранить и окно не исчезало, равно как и хоткеи не работали. После перезапуска приложения в строке меню остались только стандартные пункты макоси. Мак не видит воспроизведение музыки(не отображает в панели контроля) и не видит нажатия на медиа-кнопки. Внутренние переключение треков('L', 'K') работает. Пробовал удалять(из списка Applications), ставить старую версию(1.6.1), перезаходить в аккаунт, чистить историю и кешы всех браузеров(safari, chrome, yandexBrowser, firefox), перезапускать мак несколько раз)) Видимо, где-то всё-таки остаётся.

Надеюсь, достаточно широко расписал. Не знаю как здесь работает обратная связь, поэтому на всякий, скажу, что ник в telegram такой же. 

Из идей:
- добавить пункт для отключения анимаций "моей волны". На старых маках может подъедать графику. Да, можно закрыть окно, но это не всегда удобно
- автопереключение темы внутри сайта
- расписать как правильно полностью удалить приложения или добавить пункт удаления(хотя в моём случае это не поможет, т.к. ничего кроме пунктов макоси мне недоступно)

MacBook Air A1466, macOS Big Sur 11.6.5
![Screenshot 2022-04-08 at 23 34 22](https://user-images.githubusercontent.com/86474164/162529036-6dcae712-eef5-4719-a9e1-94dd4db8e665.png)

**Comment by juvirez** [comment]
>После перезапуска приложения в строке меню остались только стандартные пункты макоси.

Попробуй вот это: https://github.com/juvirez/yandex-music-app/issues/124#issuecomment-1086622646


>добавить пункт для отключения анимаций "моей волны". На старых маках может подъедать графику. Да, можно закрыть окно, но это не всегда удобно

#97

>автопереключение темы внутри сайта

#21

>расписать как правильно полностью удалить приложения или добавить пункт удаления

Помимо удаления app файла, нужно удалить `~/Library/Application Support/yandex-music-app`.
Все настройки приложения хранятся в `~/Library/Application Support/yandex-music-app/config.json`.

**Comment by vasnikolv** [comment]
> Попробуй вот это: [#124 (comment)](https://github.com/juvirez/yandex-music-app/issues/124#issuecomment-1086622646)

Пробовал перед отправкой репорта, но не помогло


> #97

Простите, если я недостаточно разобрался, но, кажется, это просто видео.
![Screenshot 2022-04-09 at 22 23 04](https://user-images.githubusercontent.com/86474164/162588926-2d34cd04-1b8c-43dc-9635-6fae05be1979.png)
![Screenshot 2022-04-09 at 22 23 32](https://user-images.githubusercontent.com/86474164/162588929-15f4d6d3-bd13-4d89-8366-0bcef6278135.png)
На первом скрине всё по умолчанию, на втором я просто убрал 
`<video autoplay="" muted="" loop="" disablepictureinpicture="" webkit-playsinline="" playsinline="" pip="false"> <source src="/blocks/audio-animation/i/fallback-black.mp4" type="video/mp4"> </video>` из html-кода. Проводил несколько испытаний и в итоге вывод один - видосик волны напрягает старенький i5 на 15%.



> #21

Не видел. Кстати, [роадмап, на который Вы ссылаетесь](https://github.com/juvirez/yandex-music-app/projects/2), не работает



> Помимо удаления app файла, нужно удалить

Вау! Для меня стало откровением, что `macbook-disk/Library/Application\ Support` и `macbook-disk/Users/user/Application\ Support` - разные, хотя я уже сотни раз до этого удалял оттуда файлы

**Comment by juvirez** [comment]
>проблема была не только в отображении пунктов приложения, но и в целом его использовании.

Значит проблемы уже нет?
Если проблема ещё есть, можно попробовать посмотреть логи приложения. Для этого приложение нужно запустить через терминал: `/Applications/Yandex\ Music\ Unofficial.app/Contents/MacOS/Yandex\ Music\ Unofficial`

>но, кажется, это просто видео.

Вот тут https://github.com/juvirez/yandex-music-app/issues/120#issuecomment-1094109586 пришёл в тому, что скорее всего это видео будет паузиться в некоторых случаях.

>Кстати, [роадмап, на который Вы ссылаетесь](https://github.com/juvirez/yandex-music-app/projects/2), не работает

Да, теперь нет роадмапа. Теперь приложение развивается больше не по моим хотелкам, а по репортам пользователей.

**Comment by juvirez** [comment]
Кажется, проблем тут больше нет.
