### ISSUE TITLE
Touch Bar не работает

### ISSUE THREAD

**Issue by Ptr-31** [juvirez/yandex-music-app#131]
Проблема заключается, что в версии 1.6.2 не работает Touch Bar от слова совсем. Не знаю с чем это связано, но версия под Intel. Ноут - MacBook pro 16 на i9, не думаю
, что эта информация нужна, но все же. В предыдущих версиях touch Bar работал.

**Comment by juvirez** [comment]
Раньше была интеграция с тачбарам только на уровне виджета PlayNow. После релиза [v1.7.0](https://github.com/juvirez/yandex-music-app/releases/tag/v1.7.0) приложение теперь полностью поддерживает тачбар.
