### ISSUE TITLE
Не открывается окно приложения

### ISSUE THREAD

**Issue by cuperuser** [juvirez/yandex-music-app#133]
При запуске приложения окно не появляется, получается только через док запустить песню; вот что выходит если нажать "посмотреть все окна"
<img width="1440" alt="Снимок экрана 2022-04-17 в 22 45 48" src="https://user-images.githubusercontent.com/71553656/163721947-61e8b5a0-ea98-4183-9702-f535d9e3c4ad.png">

**Comment by juvirez** [comment]
На днях будет релиз с фиксом.
А пока это можно исправить вот так: https://github.com/juvirez/yandex-music-app/issues/124#issuecomment-1086622646

**Comment by juvirez** [comment]
А вот и релиз: https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.3

**Comment by cuperuser** [comment]
спасибо вам добрые люди<3



пн, 18 апр. 2022 г. в 03:30, Aleksandr Semyonov ***@***.***>:
