### ISSUE TITLE
Не видно окно приложения

### ISSUE THREAD

**Issue by fixrom** [juvirez/yandex-music-app#135]
Пару дней назад приложение перестало отображать окно, музыка играет, кнопки переключения музыки на клавиатуре работают.

MacOS 11.6 MacBook Pro (15-inch, 2017)

**Comment by juvirez** [comment]
Попробуй вот эту версию: https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.3
Там решена эта проблема.

**Comment by fixrom** [comment]
Спасибо!
