### ISSUE TITLE
Возможность выключить иконку в Dock

### ISSUE THREAD

**Issue by dmifedorenko** [juvirez/yandex-music-app#139]
Добрый день. Спасибо за приложение, это прям глоток свежего воздуха после прослушивания в браузере.

Не могли бы вы добавить настройку для отключения иконки в Dock чтобы приложение стало фоновое и не отвлекало?

![Screenshot 2022-04-28 at 16 00 30](https://user-images.githubusercontent.com/1930019/165686974-88f3b029-5b03-419f-8fc8-d94c24cd4f96.png)

**Comment by juvirez** [comment]
Duplicate of #42
