### ISSUE TITLE
Белый экран после авторизации

### ISSUE THREAD

**Issue by Krushanov** [juvirez/yandex-music-app#140]
После входа в аккаунт осуществилась навигация на страницу Яндекс.Паспорт. Далее, я перезапустил приложение. При повторном запуске появляется только белый экран:
<img width="1413" alt="изображение" src="https://user-images.githubusercontent.com/11943655/166314570-cefa07cf-2070-4d9a-b355-0f04c481af78.png">

**Comment by kittychka** [comment]
Версия: **1.6.2**
Была такая же проблема, второй раз процесс приложения не закрывался, убила процесс через kill 9, после этого приложение загрузилось, вылетела информация о новой версии, обновила до 1.6.3. Проблема больше не возникает.

**Comment by Krushanov** [comment]
> Версия: **1.6.2** Была такая же проблема, второй раз процесс приложения не закрывался, убила процесс через kill 9, после этого приложение загрузилось, вылетела информация о новой версии, обновила до 1.6.3. Проблема больше не возникает.

 Спасибо, сработало!
