### ISSUE TITLE
Управление клавишами иногда отваливается

### ISSUE THREAD

**Issue by ra1nbow1** [juvirez/yandex-music-app#143]
Шаги воспроизведения:

1. При длительном прослушивании
2. Если включить видео или музыку в сторонней программе, а потом выключить и оставить единственный источник медиа

Кнопки ⏪⏯⏩ не работают

**Comment by juvirez** [comment]
>Кнопки ⏪⏯⏩ не работают

Это физические кнопки на F7/F8/F9? Или тачбар?

**Comment by ra1nbow1** [comment]
Физические

**Comment by vKuka** [comment]
У меня переключение не работает если в фокусе хром.  Как только переключаюсь на другую программу, то все начинает работать

**Comment by ra1nbow1** [comment]
> У меня переключение не работает если в фокусе хром. Как только переключаюсь на другую программу, то все начинает работать

Ну а должно как фоновый медиаисточник всегда переключаться

**Comment by juvirez** [comment]
Попробуйте вот это: https://github.com/juvirez/yandex-music-app/issues/167#issuecomment-1218013510
