### ISSUE TITLE
Play-Pause на одном хоткее

### ISSUE THREAD

**Issue by miheishe** [juvirez/yandex-music-app#146]
Хочется вернуть возможность play/pause на одно и тоже сочетание клавиш
Версия 1.6.3 (1.6.3)

**Comment by juvirez** [comment]
@miheishe возможность настроить хоткей на Play / Pause никуда не пропадало:
<img width="257" alt="image" src="https://user-images.githubusercontent.com/1862143/169588637-3b8a1c9f-713e-49d9-b4c6-6b243314ce73.png">

**Comment by miheishe** [comment]
В рот мне ноги!
