### ISSUE TITLE
Приложение подвисает при нестабильном подключении к интернету

### ISSUE THREAD

**Issue by fedorin-git** [juvirez/yandex-music-app#150]
**environment:**
- MacBook Pro (14-inch, 2021), Apple M1 Pro
- macOS Monterey 12.4 (21F79)
- Yandex Music Unofficial Version 1.6.3 (1.6.3)

**Steps to reproduce:**
1. Запустить приложение
2. Начать воспроизведение

**Actual result:** Трек кешируется, воспроизведение длится без перебоев, но в после окончания трека наступает длительная тишина, через какое-то время следущий трек запускается, но иногда - нет. При этом если начать кликать внутри окна приложения, то оно просто зависает. Управление воспроизведением, верхнее меню и т.д. реагирует через десятки секунд, но в конечном итоге вообще может "застыть".

**Note:** если после открытия приложения не запускать воспроизведение, то навигация по приложению работает нормально.

**Comment by saltukkos** [comment]
Вот в чём дело, а я всё свой лагающий интернет виню :)
У меня такое же поведение, отписывался в соседнем issue с интернетом https://github.com/juvirez/yandex-music-app/issues/110#issuecomment-1140244301
У вас похожим образом зависает?

**Comment by fedorin-git** [comment]
> Вот в чём дело, а я всё свой лагающий интернет виню :) У меня такое же поведение, отписывался в соседнем issue с интернетом [#110 (comment)](https://github.com/juvirez/yandex-music-app/issues/110#issuecomment-1140244301) У вас похожим образом зависает?

Абсолютно верно! Как раз собирался комментить с этим уточнением. У меня видимо в момент, когда я писал ишью, глючил ВПН. Сейчас на другом ВПН такой проблемы не наблюдается.

**Comment by vadim-hgg** [comment]
У меня абсолютно идентичные симптомы, как у @fedorin-git, на MacBook Pro 14" 2022 OS 12.5, app v. 1.6.3.
Не знаю на счет нестабильного интернета как причины... Сижу дома на вайфае. Иногда без проблем воспроизводило часами. А теперь началась фигня с воспроизведением только 1-2 композиций, а потом симптомы. Не думаю, что у меня интернет такой нестабильный. Очень хочется наслаждаться потоком музыки. А через 1-2 композиции делать force quit совсем не хочется. пока перешел обратно на браузер - но там тоже воспроизведение останавливается фактически всегда каждую композицию (но не подвисает). 

@juvirez неужели проблема реально в прерывании инета? можно как-то с этим сдружить программу?

**Comment by juvirez** [comment]
Released: [v1.7.0](https://github.com/juvirez/yandex-music-app/releases/tag/v1.7.0)

Попробуйте новый релиз и напишите ушла ли проблема.

**Comment by saltukkos** [comment]
@juvirez проверил на новом релизе, на первый взгляд в моих юзкейсах проблема ушла! При проблемах с интернетом показывается обычная всплывашка про интернет, как и в браузере, UI не зависает. После появления интернета всё прогружается и работает, спасибо1

**Comment by vadim-hgg** [comment]
> Released: [v1.7.0](https://github.com/juvirez/yandex-music-app/releases/tag/v1.7.0)
> 
> Попробуйте новый релиз и напишите ушла ли проблема.

@juvirez спасибо! сегодня слушаю музыку около 3-4 часов. программа ни разу не зависла. но проигрывание музыки останавливалось раз 5-6. иногда помогало просто нажать play. когда не помогало, пробовал нажать следующую песню - вроде, тоже не помогало, если только один раз, может. ну и всегда помогало открыть окно программы и нажать плей оттуда. 
в любом случае, это ооочень крутой фикс- что не виснет. и музыка останавливается заметно реже. (против остановки на каждой следующей или 2-3 композиции до того)

**Comment by fedorin-git** [comment]
Проблема исчезла! Спасибо!
