### ISSUE TITLE
После установки приложения перестали работать клавиши плей, вперед, назад

### ISSUE THREAD

**Issue by Kirill029** [juvirez/yandex-music-app#151]
Здравствуйте. Установил приложение и перестали работать медиа клавиши. Ничего не помогает. Вообще на маке перестали работать. macOS Big Sur 11.6.6. Можно как то их починить?

**Comment by maxiiusa** [comment]
@Kirill029 Попробуйте вот это, пожалуйста: https://github.com/juvirez/yandex-music-app/issues/167#issuecomment-1218013510

**Comment by maxiiusa** [comment]
@Kirill029 если вам помогло данное решение, не могли бы вы закрыть ишью?
