### ISSUE TITLE
Не работает приложение 

### ISSUE THREAD

**Issue by come0th3r** [juvirez/yandex-music-app#152]
Не знаю почему, но сервис прогрузил морду + показывает плейлисты, но не работает почему то произведение ни в какую

MCBKP2020 M1
![image](https://user-images.githubusercontent.com/98780286/170337109-7f3c7169-4445-4c37-9897-36650fa28975.png)

**Comment by juvirez** [comment]
А через браузер?
Бывает, что сервис Яндекс Музыка становится недоступным. Тут ничего не поделаешь со стороны приложения.

**Comment by maxiiusa** [comment]
@come0th3r не могли бы подсказать, пожалуйста, актуальна ли проблема в данный момент?
