### ISSUE TITLE
Темная тема оформление приложения 

### ISSUE THREAD

**Issue by Kybik420** [juvirez/yandex-music-app#155]
Здравствуйте, не хватает темной темы оформление в приложение.
В будущих обновлениях есть возможность увидеть?)

**Comment by d-dyachkov** [comment]
@Kybik420 тема настраивается через саму Яндекс.Музыку. Для этого нужно перейти "Настройки -> Прочее -> Тёмная тема". После этого если откроете музыку в браузере, то тема так же будет тёмная

**Comment by maxiiusa** [comment]
@Kybik420 если вам помогло данное решение, не могли бы вы закрыть ишью?

**Comment by Kybik420** [comment]
Спасибо
