### ISSUE TITLE
Как выбрать русский язык?

### ISSUE THREAD

**Issue by slepoy1** [juvirez/yandex-music-app#157]
Существует способ смены англоязычного интерфейса на русский язык? Спасибо.
<img width="233" alt="Снимок экрана 2022-06-29 в 21 17 12" src="https://user-images.githubusercontent.com/56146343/176507734-a86b8525-bac6-40d0-bfaf-174160b6127f.png">
<img width="507" alt="Снимок экрана 2022-06-29 в 21 17 03" src="https://user-images.githubusercontent.com/56146343/176507749-e35b2d7c-b304-4760-b85b-6d3c55c58546.png">

**Comment by juvirez** [comment]
Меню было переведено на русский в версии [v1.8.0](https://github.com/juvirez/yandex-music-app/releases/tag/v1.8.0)
