### ISSUE TITLE
проблема на mackbook 16 m1 с челкой

### ISSUE THREAD

**Issue by martina4ever** [juvirez/yandex-music-app#160]
1. если выбрать в настройках пункт show menubar icon и уже кликнув по иконке выбрать Show song in menubar, то иконка [пропадает](https://disk.yandex.ru/i/EXlfllweHhNJiw). если поставить на паузу - [появляется](https://disk.yandex.ru/i/TlRv-K2XxW_BiA) и так панель постоянно прыгает если включать и останавливать воспроизведение.

2. если во время воспроизведения макбук переключился с одного вайфая на другой с плохим интернетом или если интернет пропал или пропал и потом появился, то на следующем треке все начинает дико виснуть(и макос тоже) пока принудительно не завершишь и не запустишь заново программу

**Comment by saltukkos** [comment]
Второй пункт - известная бага. https://github.com/juvirez/yandex-music-app/issues/150

**Comment by juvirez** [comment]
Первый пункт воспроизвёл, но ничего с этим сделать не могу — так работает MenuBar в MacOS.
Если до чёлки не влезает, следующие иконки не отображаются.
