### ISSUE TITLE
Аутентификация через гугл не работает

### ISSUE THREAD

**Issue by Vyacheslau** [juvirez/yandex-music-app#163]
Шаги
1. Открыть приложение
2. Нажать "Войти" в правом верхнем углу
3. "Войти с помощью" --> Google

Ожидаемый результат: пользователь аутентифицирован и может пользоваться Яндекс Музыка под своим аккаунтом.

Реальный результат:
<img width="1534" alt="image" src="https://user-images.githubusercontent.com/3686975/178687358-ab2c4035-8f57-485a-b1d6-7340dca4a3d5.png">
При этом аутентификация не происходит.

P.S. спасибо за то, что создали это приложение! Надеюсь смогу им пользоваться, когда этот баг будет пофиксан. Респект вам!

**Comment by juvirez** [comment]
Да, это известная проблема и решить её не просто. Да и смысла особо нет от входа по логину стороннего сервиса.
В любом случае придётся открывать окно гугл аворизации внутри приложения, а в окне приложения вы будете не авторизованы. А значит в любом случае нужно будет вводить логин и пароль, но от гугла.

Рабочие методы входа: по логину/паролю, по смс или по QR.
