### ISSUE TITLE
Добавить в менюшку, которое вылезает на иконке в строке меню, пункт "показать окно программы"

### ISSUE THREAD

**Issue by russinow** [juvirez/yandex-music-app#164]
для меня самый быстрый и всегда доступный способ доступа до некоторых приложений - через строку меню вверху экрана. И все бы хорошо, но в менюшке нашего приложения нет пункта "показать окно программы". Из-за этого приходится лезть в Dock, а он по умолчанию прячется, ждать когда он выскочит и только потом жать на иконку программы. Очень не удобно.

эта идея хорошо стыкуется с идеей скрыть значок приложения в доке #139, #54, #42

**Comment by juvirez** [comment]
Released: [v1.7.0](https://github.com/juvirez/yandex-music-app/releases/tag/v1.7.0)
