### ISSUE TITLE
Интерфейс

### ISSUE THREAD

**Issue by isqhakov** [juvirez/yandex-music-app#166]
Сделайте под цвет интерфейса

<img width="1280" alt="Снимок экрана 2022-08-12 в 16 09 24" src="https://user-images.githubusercontent.com/58817999/184342450-a544171b-2124-4d8f-8266-ced64c77efa3.png">

**Comment by juvirez** [comment]
А какой тут цвет интерфейса? Можно для примера скриншот другого приложения, который под цвет интерфейса?

**Comment by isqhakov** [comment]
Извиняюсь неправильно высказался)
Имею ввиду типо так:
<img width="1280" alt="Снимок экрана 2022-08-16 в 00 50 56" src="https://user-images.githubusercontent.com/58817999/184707810-01bcdab4-6564-48e9-ab80-8fff97a5cc8f.png">

**Comment by juvirez** [comment]
Поддержка тёмной темы?
Тёмная тема есть в настройках Яндекс Музыки: https://github.com/juvirez/yandex-music-app/issues/155#issuecomment-1154773402

**Comment by juvirez** [comment]
duplicate of #155
