### ISSUE TITLE
Не работают медиа клавиши

### ISSUE THREAD

**Issue by uiro1** [juvirez/yandex-music-app#167]
Не работают медиа клавиши, кажется, теперь вообще нигде.
Версия 1.6.3
MacBook Air m1 2020, Mac OS 12.4
Переустановка не помогает.

**Comment by uiro1** [comment]
Решилось включением демона
launchctl load -w /System/Library/LaunchAgents/com.apple.rcd.plist

**Comment by artembaechka** [comment]
Спамбо огромное, решил эту проблему спустя 5 дней неудобств
