### ISSUE TITLE
Не отображаются иконки на touch bar 

### ISSUE THREAD

**Issue by stdcion** [juvirez/yandex-music-app#168]
**Устройство: MacBook Pro (13-inch, M1, 2020)**
**OS: macOS Monterey 12.5.1**
**Версия приложения: v1.7.0**
Установлено с помощью homebrew, но пробовал ставить напрямую с github.
**Результат:**
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/92171388/185788796-cd6cb013-c805-4818-9bec-8876947e1b3d.png">

Скорее всего проблема связана с этим [коммитом](https://github.com/juvirez/yandex-music-app/commit/5dde818c7d6ba9ff1d7a356366fd36ecaa1e732a), где юникод символы в label, были заменены на что-то другое. Возможно была ориентация на конкретный шрифт?

**Comment by danial031193** [comment]
Та же проблема на MacBook Pro (15-inch, 2018), ставил с гитхаб

**Comment by juvirez** [comment]
Починил: https://github.com/juvirez/yandex-music-app/releases/tag/v1.7.1
Проверьте плиз

**Comment by stdcion** [comment]
Да, спасибо большое, работает! И значок лайка/дизлайка тоже правильно переключается.
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/92171388/189202311-b9436522-7b0a-4233-9688-8fed5715ec8f.png">
