### ISSUE TITLE
Интерфейс нейромузыки

### ISSUE THREAD

**Issue by poul666** [juvirez/yandex-music-app#169]
Яндекс добавил нейромузыку в приложение на ios, но в приложение для mac данный интерфейс не добавился.

**Comment by Bagasl** [comment]
Пока сам Яндекс не добавит его в веб версию - думаю не стоит ждать появления в этом приложении

**Comment by maxiiusa** [comment]
@poul666 решение данного вопроса действительно на стороне Яндекс. Не могли бы вы, пожалуйста, закрыть ишью?
