### ISSUE TITLE
Плэй/Пауза

### ISSUE THREAD

**Issue by bambookchos** [juvirez/yandex-music-app#17]
После нажатия плэй/пауза (F8), музыка ставится на паузу. Если нажать еще раз, в программе будет показано, что музыка воспроизводится, но звука нет, и время и прогрессбар не двигаются.

Если нажать плэй/пауза (F8) еще раз стравится пауза, и уже после этого при нажати музыка включится.

То есть что поставить на паузу мне нужно нажать один раз, а вот чтобы продолжить нужно нажать еще 3 раза.

**Comment by juvirez** [comment]
Судя по всему, у тебя установлена не финальная версия 1.5.0.
В ней был такой баг — app подписывался и на медиа хоткеи, и на MacOS MediaService.

Попробуй установить последнюю версию: https://github.com/juvirez/yandex-music-app/releases/tag/v1.5.0

**Comment by bambookchos** [comment]
> Version 1.5.0 (1.5.0)

**Comment by juvirez** [comment]
Да, версия одинаковая, но сборка отличается. Сборка с этим багом была опубликована как pre-release в течении нескольких часов. Не думал, что кто-то успеет скачать сборку с багом :)

Попробуй установить сборку от сюда: https://github.com/juvirez/yandex-music-app/releases/tag/v1.5.0

**Comment by bambookchos** [comment]
Отсюда и ставил :)
Заметил что воспроизводится только если установить Accessibility для приложения.

Если ставлю Accessibility - плэй/пауза работает с багом через обычную кнопку на клаве (в конфигах приложения на плэй никакой кнопки не стоит)
А без Accessibility нет хоткеев на лайк/ дизлайк :(

**Comment by juvirez** [comment]
Всё таки попробуй переустановить — должно помочь.
Фикс был неделю назад (92a10f460fa9ce307b074bf306f3be1596d37716). А ты, видимо, успел скачать версию с багом.

**Comment by bambookchos** [comment]
Я зафайлил баг в день установки, а 2 дня назад переустановил

**Comment by juvirez** [comment]
О, я воспроизвёл на другом маке.

**Comment by juvirez** [comment]
@bambookchos готово: https://github.com/juvirez/yandex-music-app/releases/tag/v1.5.1

**Comment by bambookchos** [comment]
@juvirez Да, проблема прошла.
Есть еще одна касательно хоткеев. Завести отдельно или тут?

**Comment by juvirez** [comment]
Давай отдельно
