### ISSUE TITLE
проблема с лайками в полноэкранном режиме

### ISSUE THREAD

**Issue by sergeyklochko** [juvirez/yandex-music-app#170]
Сейчас лайк для уже отмеченной понравившейся песни приводит к тому, что с нее снимается отметка "нравится".
Это в свою очередь приводит к тому, что, будучи в полноэкранном режиме или если окно плеера закрыто другими окнами, невозможно понять что произойдет с песней, если ты нажмешь сочетание клавиш для лайка. Получит она лайк или снимется ранее установленный.

В силу того, что этот механизм, судя по всему, реализован на стороне яндекса видится следующее решение - Добавить настройку, которая, в случае нажатия лайка, позволяет игнорировать это нажатие если песня уже имеет статус понравившейся.

Сейчас приходится переключаться в плеер, чтобы понять есть у песни уже лайк или нет, чтобы случайно не снять его.

**Comment by juvirez** [comment]
1. Если выдать приложению права на нотификации, при переключении like/unlike через хоткеи оно будет отображать нотификацию с актуальным статусом (с сердечком или без).
2. У вас задан хоткей like/unlike. Но есть отдельная опция только для like, она работает так, как вам нужно:
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/1862143/188503288-db0fcfb2-7c97-4751-9e4d-4259ab378933.png">
