### ISSUE TITLE
Показывается реклама с подпиской 

### ISSUE THREAD

**Issue by IronGunYT** [juvirez/yandex-music-app#171]
Устройство: MacBook Air (13-inch, M1, 2020)
OS: macOS Monterey 12.5
Версия приложения: v1.7.0
У меня есть подписка на яндекс музыку, но мне всё равно отображается реклама
<img width="1440" alt="Снимок экрана 2022-09-06 в 20 11 48" src="https://user-images.githubusercontent.com/23254987/188698304-73590978-9bc7-4cda-a2b1-c8d995577e7e.png">

**Comment by juvirez** [comment]
Приложение на это никак не влияет.
Нужно репортать о проблеме в саму Яндекс Музыку: https://yandex.ru/support/music/troubleshooting/feedback.html

**Comment by IronGunYT** [comment]
В онлайн версии всё хорошо - рекламы нет. Может что-то с авторизацией?

**Comment by juvirez** [comment]
Хм, очень странно.
Авторизацией приложение тоже никак не управляет.
Можно попробовать почистить кеш приложения — нужно удалить папку `/Users/<user>/Library/Application\ Support/yandex-music-app/Cache/`

**Comment by IronGunYT** [comment]
Не помогло, реклама всё ещё показывается. Пробовали проводить ручное тестирование с премиумом на macos?

**Comment by juvirez** [comment]
>Пробовали проводить ручное тестирование с яндекс плюс на macos?

конечно

**Comment by shveetsov** [comment]
У меня все хорошо

**Comment by IronGunYT** [comment]
Возможно из-за того, что я покупал подписку не через сайт Яндекса, а через оператора Life и плачу с баланса

**Comment by IronGunYT** [comment]
Проблема решилась через поддержку Яндекса. Похоже, было что-то с аккаунтом

**Comment by IronGunYT** [comment]
Баг всё ещё сохраняется. Пытался связываться с поддержкой яндекса, но ничего толкового не ответили

**Comment by mafuuu-dev** [comment]
Такая же проблема! Какую информацию нужно предоставить для дебага? Заметил, что часто появляется реклама когда я переключаю трек вручную и иногда при воспроизведении.

**Comment by mafuuu-dev** [comment]
> Хм, очень странно. Авторизацией приложение тоже никак не управляет. Можно попробовать почистить кеш приложения — нужно удалить папку `/Users/<user>/Library/Application\ Support/yandex-music-app/Cache/`

удалял приложение вместе с папкой "yandex-music-app". полностью переустанавливал его, не помогло

**Comment by IronGunYT** [comment]
> > Хм, очень странно. Авторизацией приложение тоже никак не управляет. Можно попробовать почистить кеш приложения — нужно удалить папку `/Users/<user>/Library/Application\ Support/yandex-music-app/Cache/`
> 
> удалял приложение вместе с папкой "yandex-music-app". полностью переустанавливал его. не помогло ;(

Я связался с поддержкой Яндекса. Судя по всему, у меня не работа правило подписка Яндекс плюс(возможно потому, что они недавно меняли условия). У меня писалось что у меня нет подписки в Яндекс еде и такси, поэтому я написал об этом в поддержку и судя по всему мне как-то инактивировали подписку. С тех пор я почистил приложение ещё раз и баг не встречался

**Comment by IronGunYT** [comment]
> > > Хм, очень странно. Авторизацией приложение тоже никак не управляет. Можно попробовать почистить кеш приложения — нужно удалить папку `/Users/<user>/Library/Application\ Support/yandex-music-app/Cache/`
> > 
> > 
> > удалял приложение вместе с папкой "yandex-music-app". полностью переустанавливал его. не помогло ;(
> 
> Я связался с поддержкой Яндекса. Судя по всему, у меня не работа правило подписка Яндекс плюс(возможно потому, что они недавно меняли условия). У меня писалось что у меня нет подписки в Яндекс еде и такси, поэтому я написал об этом в поддержку и судя по всему мне как-то инактивировали подписку. С тех пор я почистил приложение ещё раз и баг не встречался

Писал так:
```Добрый день. Я покупаю подписку Яндекс плюс через мобильного оператора Life. 
Мой аккаунт: …
При авторизации через аккаунт в приложении Яндекс музыки всё хорошо. Однако если я пытаюсь авторизоваться на сайте Яндекса, или в приложениях Яндекс еды/такси, мне только предлагают купить подписку и, как я понял, не дают бонусы. Как это можно починить?```
Ответ: ```Здравствуйте! 

Благодарю за ожидание.

Мы кое-что исправили. Теперь Плюс активен на вашем аккаунте  ```

**Comment by mafuuu-dev** [comment]
> > > Хм, очень странно. Авторизацией приложение тоже никак не управляет. Можно попробовать почистить кеш приложения — нужно удалить папку `/Users/<user>/Library/Application\ Support/yandex-music-app/Cache/`
> > 
> > 
> > удалял приложение вместе с папкой "yandex-music-app". полностью переустанавливал его. не помогло ;(
> 
> Я связался с поддержкой Яндекса(через яндекс сообщения(мессенджер)). Судя по всему, у меня не работа правило подписка Яндекс плюс(возможно потому, что они недавно меняли условия). У меня писалось что у меня нет подписки в Яндекс еде и такси, поэтому я написал об этом в поддержку и судя по всему мне как-то инактивировали подписку. С тех пор я почистил приложение ещё раз и баг не встречался

спасибо огромное! а то эта штука довольно сильно раздражает) очень радует, что проблема решаема

**Comment by mafuuu-dev** [comment]
> > > > Хм, очень странно. Авторизацией приложение тоже никак не управляет. Можно попробовать почистить кеш приложения — нужно удалить папку `/Users/<user>/Library/Application\ Support/yandex-music-app/Cache/`
> > > 
> > > 
> > > удалял приложение вместе с папкой "yandex-music-app". полностью переустанавливал его. не помогло ;(
> > 
> > 
> > Я связался с поддержкой Яндекса. Судя по всему, у меня не работа правило подписка Яндекс плюс(возможно потому, что они недавно меняли условия). У меня писалось что у меня нет подписки в Яндекс еде и такси, поэтому я написал об этом в поддержку и судя по всему мне как-то инактивировали подписку. С тех пор я почистил приложение ещё раз и баг не встречался
> 
> Писал так:
> 
> ```
> Мой аккаунт: …
> При авторизации через аккаунт в приложении Яндекс музыки всё хорошо. Однако если я пытаюсь авторизоваться на сайте Яндекса, или в приложениях Яндекс еды/такси, мне только предлагают купить подписку и, как я понял, не дают бонусы. Как это можно починить?
> ```
> 
> Ответ:
> 
> ```
> Благодарю за ожидание.
> Мы кое-что исправили. Теперь Плюс активен на вашем аккаунте 
> ```

расскажу как у меня проблема решилась. 
когда мне нужно было оплачивать подписку она автоматически не пролонгировалась и пришлось вручную оформить ее по новой, после этого проблема исчезла, по крайней мере регресса не наблюдаю

всем спасибо за помощь в решение вопроса!)

**Comment by IronGunYT** [comment]
Предлагаю добавить описание решения в README: #183
