### ISSUE TITLE
Кастомизация

### ISSUE THREAD

**Issue by surik-simyan** [juvirez/yandex-music-app#173]
Здравствуйте, для той же Spotify есть Spicetify который как я понял работает как CSS Inject. Можно ли для этого клиента сделать что то подобное?

**Comment by juvirez** [comment]
Возможность делать CSS Inject есть.
Если кто-либо сделает достойные темы — приму и добавлю.

**Comment by surik-simyan** [comment]
Хорошо, спасибо.
