### ISSUE TITLE
Полоса прокрутки

### ISSUE THREAD

**Issue by CornyRust** [juvirez/yandex-music-app#175]
Здравствуйте , можете пожалуйста исправить баг полосы прокрутки ? При изменении на темную тему в настройках яндекса , полоса прокрутки остается белой .. очень бросается в глаза

**Comment by maxiiusa** [comment]
@CornyRust не могли бы вы, пожалуйста, закрыть ишью?

**Comment by juvirez** [comment]
Duplicate of #94
