### ISSUE TITLE
Добавить перемотку трека

### ISSUE THREAD

**Issue by MichaelMironenko** [juvirez/yandex-music-app#176]
Было бы здорово сделать перемотку трека по длительному нажатию кнопки следующего трека. И соответственно перемотку назад по кнопке предыдущего трека. 

Иногда хочется промотать трек на 10-20 секунд с клавиатуры, не переходя в плеер.

**Comment by juvirez** [comment]
В MacOS такое невозможно сделать стандартными средствами. Даже Spotify такое не поддерживает.
Добавлю отдельный хоткей на перемотку +/- 5 секунд.

**Comment by juvirez** [comment]
Добавлено в [v1.8.0](https://github.com/juvirez/yandex-music-app/releases/tag/v1.8.0)
