### ISSUE TITLE
Большое количество подпроцессов

### ISSUE THREAD

**Issue by MichaelMironenko** [juvirez/yandex-music-app#181]
У программы аж 7 детей. Нормально ли это или является следствием каких-то утечек?

![Screenshot 2022-11-14 at 17 58 55](https://user-images.githubusercontent.com/721222/201692626-53bbd6d4-f27e-4aa5-ab7c-f5069977bea6.png)

**Comment by juvirez** [comment]
Так работает electron ¯\\\_(ツ)_/¯
Никаких утечек не должно быть.
