### ISSUE TITLE
Убирать модальное окно "Поделиться" после действия

### ISSUE THREAD

**Issue by romant094** [juvirez/yandex-music-app#184]
Предложение в сабже.
Сейчас оно убирается, только когда выбрано действие `HTML-код`. При двух других действиях что-то происходит, но окно не пропадает. Хотелось бы, чтобы оно исчезало после целевого действия.
<img width="928" alt="image" src="https://user-images.githubusercontent.com/37865987/203975684-392ccab5-af41-4cc3-bb75-bbd9ea68a162.png">

**Comment by juvirez** [comment]
Конечно, это уже баг в самой яндекс музыке, но можно попробовать починить в приложении.

**Comment by juvirez** [comment]
Не стал возиться с этим попапом — просто сделал пункт меню с хоткеем для копирования урла текущего трека.

Добавлено в [v1.8.0](https://github.com/juvirez/yandex-music-app/releases/tag/v1.8.0)
