### ISSUE TITLE
Медиаклавиши в приложении

### ISSUE THREAD

**Issue by JakeBadlands** [juvirez/yandex-music-app#186]
Было бы неплохо сделать чтобы они работали. В одном подобном "приложении" это работает, но разработчик забросил дело https://github.com/debug45/Yandex-Music, но Ваше приложение мне нравится больше

**Comment by juvirez** [comment]
А они не работают?

**Comment by JakeBadlands** [comment]
К сожалению нет. MacBook pro 2021 m1

**Comment by juvirez** [comment]
Попробуйте вот это: https://github.com/juvirez/yandex-music-app/issues/167#issuecomment-1218013510

**Comment by JakeBadlands** [comment]
Добрый вечер! 
Спасибо, помогло!

**Comment by maxiiusa** [comment]
@juvirez если вам помогло данное решение, не могли бы вы закрыть ишью?
