### ISSUE TITLE
Отображение названия трека ломает иконку в баре

### ISSUE THREAD

**Issue by zhmpng** [juvirez/yandex-music-app#187]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/75923630/204343912-155d1c46-4214-4d58-8b10-d548f4faea2a.png">
MacBook Pro 14 2021 Ventura 13.0.1 
Версия программы 1.7.1 

Если проставить чекбокс отображения песни в баре, то после применения данной функции иконка вовсе пропадает и различными махинациями без удаления приложения ее не получается вернуть. 
https://github.com/juvirez/yandex-music-app/blob/d27af72dac90bc6a083bccca06068ebd2b7eaa53/src/main/features/dockMenu.js#L183

Могу предположить, что это как то связано с бровью у данной линейки маков, но другие приложения в целом спокойно заезжают за нее.

**Comment by juvirez** [comment]
Так работает MenuBar в MacOS, ничего с этим сделать не могу.
Если до чёлки пункт не влезает — он перестаёт отображаться полностью.

Можно попробовать ограничить максимальный размер названия трека, сейчас ограничение в 45 символов.
Нужно добавить пропертю `tray-song-label-length` в конфиг `/Users/${USER}/Library/Application Support/yandex-music-app/config.json`
