### ISSUE TITLE
Черный экран при закрытии в полном экране

### ISSUE THREAD

**Issue by kin4stat** [juvirez/yandex-music-app#189]
Черный экран при закрытии приложения в полном экране

**Comment by maxiiusa** [comment]
Не могу воспроизвести данный баг. Не могли бы предоставить, пожалуйста, более подробные шаги для воспроизведения данной проблемы или приложить запись экрана?

**Comment by kin4stat** [comment]
https://user-images.githubusercontent.com/26118089/212397169-ce687e1b-d364-488a-a032-9e490707b7bc.mov

**Comment by juvirez** [comment]
Исправлено в [v1.8.0](https://github.com/juvirez/yandex-music-app/releases/tag/v1.8.0)
