### ISSUE TITLE
Не работает Touch Bar

### ISSUE THREAD

**Issue by HardLight00** [juvirez/yandex-music-app#19]
Перестали показываться настройки управления в Touch Bar.
Скорее всего связано с обновлением Mac OS

**Comment by juvirez** [comment]
После перезагрузки системы тоже не отображаются?

У меня тоже бывало что переставало отображаться — помогала лишь перезагрузка.
Исследовал и пришёл к выводу, что скорее всего это баг MacOS, потому что смог воспроизвести подобное поведение и в Apple Music.
