### ISSUE TITLE
web/mobile interface  

### ISSUE THREAD

**Issue by m04kA** [juvirez/yandex-music-app#190]
Можно ли как-то переключаться между интерфейсами. У меня сейчас подгружается интерфейс с web, но мне удобнее мобильный. Странно то, что при самой первой установке был как раз мобильная версия, но после переустановки системы я снова скачал приложение и там уже был web. Можно ли что-то сделать?

**Comment by juvirez** [comment]
Возможно вы устанавливали какое-то другое приложение?
Это приложение всегда было лишь обёрткой над веб версии яндекс музыки.
