### ISSUE TITLE
Скачивали треков

### ISSUE THREAD

**Issue by Pavel-Fomin** [juvirez/yandex-music-app#194]
было бы круто, впилить плагин для скачивания треков, как в гугловском расширении, но к этому добавить проверку на уже скаченные треки. Такое многие диджеи оценят, можно даже за такое брать деньги

**Comment by gormonn** [comment]
@Pavel-Fomin каким образом брать деньги? По-пиратски что ли?

**Comment by Pavel-Fomin** [comment]
> @Pavel-Fomin каким образом брать деньги? По-пиратски что ли?

Ну можно и по-пиратски, если взгляды позволяют)
Все равно их-так-и-так скачивают, через бота в телеге, поскольку нельзя купить трек, а можно только арендовать(
