### ISSUE TITLE
Открытие приложением ссылок

### ISSUE THREAD

**Issue by ArturKontrabaev** [juvirez/yandex-music-app#199]
Добрый день, 

Никак не могу настроить чтобы приложение открывало ссылки
Беру любую ссылку https://music.yandex.ru/album/12118149/track/71245764 
Дальше настраиваю например в Velja или Choosy открытие этой ссылки не в браузере, а в приложении

и получаю ошибку 404
<img width="387" alt="SCR-20230216-6gp" src="https://user-images.githubusercontent.com/60569907/219242800-d016268f-499e-49d1-a01b-c2648c9ca9e6.png">

Единственный вариант который сейчас нашел - это открывать ссылку в Google Chrome, а в нем ставить расширение которое позволяет открыть музыку в приложении, что не удобно, так как остается висеть открытое окно хрома.

Вопросы:
1. можно ли добавить каким то образом перехват с помощью приложения ссылок открываемых, чтобы не использовать сторонний софт ? 
2. если нет, то в каком формате надо передать ссылку в приложение, чтобы она открылась ? Хром как то же это делает ?  возможно я найду приложение которое умеет еще и ссылку обрабатывать
3. можно ли добавить в приложение поддержку ссылок по типу выше, чтобы они открывались минуя хром ? 

Спасибо

**Comment by juvirez** [comment]
Duplicate of #122
Починено в [v1.8.0](https://github.com/juvirez/yandex-music-app/releases/tag/v1.8.0)

**Comment by ArturKontrabaev** [comment]
работает спасибо, но работает только для ссылок типа https://music.yandex.ru
почему то у некоторых когда шарят ссылка формата https://music.yandex.com, можно и для таких добавить ? 
спасибо
