### ISSUE TITLE
Стандартные клавиши macbook для включения следующего трека

### ISSUE THREAD

**Issue by ivan45654** [juvirez/yandex-music-app#20]
После попытки настроить глобальные клавиши перестали работать стандартные клавиши macbook для включения следующего трека и паузы. Пытался удалять приложение и его файлы в ~/Library но толку 0 (может не нашел где эта настройка хранится), клавиши так и не начали работать.
Как сделать сброс приложения?
Есть ли возможность как-то оставить работать стандартные клавиши для следующей песни но при этом настроить свои для лайка и дислайка песни?

upd: пока откатился на v1.5.0 вроде как все заработало. В глобальные хоткейс пока не залезаю

**Comment by juvirez** [comment]
>Как сделать сброс приложения?

Чтобы полностью сбросить приложение, можно попробовать удалить папку `~/Library/Application Support/yandex-music-app`.

>Есть ли возможность как-то оставить работать стандартные клавиши для следующей песни но при этом настроить свои для лайка и дислайка песни?

Медиа клавиши должны работать безусловно, вне зависимости настроены хоткеи или нет.
Возможно, дело в конкретных настроенных комбинациях клавиш.
Попробуй воспроизвести ещё раз и приложить сюда содержимое файла `~/Library/Application Support/yandex-music-app/Settings`.
