### ISSUE TITLE
Перемотка в начало трека на хоткей перемотки назад

### ISSUE THREAD

**Issue by Tamerlanchiques** [juvirez/yandex-music-app#201]
Иногда хочется послушать текущий трек сначала, но, при текущей реализации, плеер переключается на предыдущей трек. Думаю, можно было бы сделать как в Spotify, где единичное нажатие возвращает в начало трека, а двойное переключает плеер на предыдущий трек. При этом, если быстро переключать треки назад, то достаточно одного нажатия.

**Comment by juvirez** [comment]
Исправлено в [v1.8.0](https://github.com/juvirez/yandex-music-app/releases/tag/v1.8.0)
