### ISSUE TITLE
Как сменить аккаунт в приложении?

### ISSUE THREAD

**Issue by Ashurov** [juvirez/yandex-music-app#203]
Не нашел способ сменить аккаунт в приложении. Как это можно сделать?
Пробовал удалить и установить заново.

**Comment by maxiiusa** [comment]
@Ashurov https://share.cleanshot.com/0qb3T6qy

**Comment by Ashurov** [comment]
Спасибо ) у меня размер окна оказывается был уменьшен и не было видно аватарки.
