### ISSUE TITLE
Обновление до версии 1.8.0 для Intel и сброс настроек (невозможность настройки)

### ISSUE THREAD

**Issue by slepoy1** [juvirez/yandex-music-app#204]
Здравствуйте. После обновления (замены) приложения 1.7.х до версии 1.8.0 для Intel на Mac OS 13.3.1 (a):
1) интерфейс по-прежнему на английском языке;
2) нет реакции на нажатие медиа-клавиш (плей, след., пред. и т.д);
3) нет реакции на изменение в настройках приложения: темная тема, тип плеера;
4) в строке меню более не отражается наименование трека и прочая информация, заданная в настройках предыдущей версии приложения;
5) в настройках MacOS (конфиденциальность и безопасность, клавиатура) нет ничего, что указывало бы на то, что приложению следует предоставить "больше прав".
6) в строке меню для приложения нет каких-либо настроек (кнопки Settings), позволяющих выбрать все вышесказанное.

Спасибо.

<img width="777" alt="Снимок экрана 2023-05-09 в 17 00 34" src="https://github.com/juvirez/yandex-music-app/assets/56146343/15380364-7482-44f1-8192-8344072ffc81">
<img width="771" alt="Снимок экрана 2023-05-09 в 17 00 30" src="https://github.com/juvirez/yandex-music-app/assets/56146343/a3ce525f-d17b-44e0-b9c1-fd0b5c903d46">
<img width="772" alt="Снимок экрана 2023-05-09 в 17 00 24" src="https://github.com/juvirez/yandex-music-app/assets/56146343/cc8af8a3-37f4-4222-af69-82eca50a4005">
<img width="774" alt="Снимок экрана 2023-05-09 в 17 00 18" src="https://github.com/juvirez/yandex-music-app/assets/56146343/fad42f90-e457-42bc-ab52-3b8ec83266ff">
<img width="638" alt="Снимок экрана 2023-05-09 в 17 00 53" src="https://github.com/juvirez/yandex-music-app/assets/56146343/fa6c2aca-315c-4366-a774-a333679c7bff">

**Comment by juvirez** [comment]
@slepoy1 @kin4stat Можете скинуть сюда логи приложения?

Для этого нужно запустить приложение следующим образом:
1. Открыть в Finder каталог с приложениями
2. Правой кнопкой на иконке приложения — Show Package Contents
3. Запустить файл Contents / MacOS / Yandex Music Unofficial
4. И всё что отобразится в консоле скинуть сюда.

**Comment by juvirez** [comment]
Кажется воспроизвёл со сборкой для intel.
```
electron-media-service/build/Release/electron_media_service.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
```

**Comment by juvirez** [comment]
Пробуем: [v1.8.1](https://github.com/juvirez/yandex-music-app/releases/tag/v1.8.1)

**Comment by slepoy1** [comment]
Здравствуйте. В версии 1.8.1 вышесказанные проблемы не актуальны.
Обнаружил только отсутствие перевода этих строк:
<img width="346" alt="Снимок экрана 2023-05-11 в 23 26 39" src="https://github.com/juvirez/yandex-music-app/assets/56146343/29095885-3de0-44bc-b77e-ca9d061efb19">
Спасибо.

**Comment by juvirez** [comment]
Спасибо!

>Обнаружил только отсутствие перевода этих строк

Пока перевод есть только у меню.
