### ISSUE TITLE
Переключение языка через config

### ISSUE THREAD

**Issue by danial031193** [juvirez/yandex-music-app#208]
Было бы здорово чтобы через config был доступ к переключению языка обратно на english

**Comment by juvirez** [comment]
Приложение берёт текущий язык из системы.
Но можно переопределить дефолтный язык для конкретного приложения.
System Settings — General — Language & Region — Applications

<img width="713" alt="image" src="https://github.com/juvirez/yandex-music-app/assets/1862143/5f4f0bd2-038a-43b6-8aa0-49e8c9453e60">

**Comment by danial031193** [comment]
> Приложение берёт текущий язык из системы. Но можно переопределить дефолтный язык для конкретного приложения. System Settings — General — Language & Region — Applications
> 
> <img alt="image" width="713" src="https://user-images.githubusercontent.com/1862143/238751042-5f4f0bd2-038a-43b6-8aa0-49e8c9453e60.png">

Спасибо, не знал о таком функционале, думаю что ишью не актуально 🙂
