### ISSUE TITLE
проблема с темной/светлой темой.

### ISSUE THREAD

**Issue by sergeyklochko** [juvirez/yandex-music-app#209]
сегодня после сбоя приложение заявило, что отныне тема жестко привязана к теме операционной системы.
на самом сайте яндекс музыки нет проблем поменять тему оформления.
где искать причину и как вернуть светлую тему при темной системной?

**Comment by juvirez** [comment]
Чтобы тема была зафиксирована, нужно снять галку Settings — Sync with OS theme

**Comment by sergeyklochko** [comment]
подскажите, где эта галка?
и как так могло получится, что она сама вдруг включилась?

**Comment by juvirez** [comment]
Это фича такая :) #21
<img width="722" alt="image" src="https://github.com/juvirez/yandex-music-app/assets/1862143/77730795-b1ef-406a-82c3-756dc22b127e">

**Comment by sergeyklochko** [comment]
Спасибо, помогло. Остается вопрос с чего оно вдруг включилось.

**Comment by juvirez** [comment]
Приложение обновилось и включилась эта фича: #21 
Решил включить её по умолчанию, но добавил алерт при изменении темы:
<img width="928" alt="image" src="https://github.com/juvirez/yandex-music-app/assets/1862143/2bb32954-48ee-49e7-acad-6c80e1bc7bb9">
