### ISSUE TITLE
Feature request: Управление темой плеера

### ISSUE THREAD

**Issue by ekzotech** [juvirez/yandex-music-app#21]
Привет! Огромное спасибо за приложение!

Есть ли возможность отслеживать переключение между светлой/тёмной темой в системе и, соответственно, переключать "Тёмная тема" в "Прочее" (в настройках Яндекс.Музыки)?
Было бы очень здорово, если б не надо было руками переключать.

**Comment by juvirez** [comment]
Привет! Спасибо за отзыв и донат! ☺️

Эта фича у меня первая в списке планов на следующую версию.
Роадмап проекта можно посмотреть [тут](https://github.com/juvirez/yandex-music-app/projects/2).

**Comment by juvirez** [comment]
Реализовано в [v1.8.0](https://github.com/juvirez/yandex-music-app/releases/tag/v1.8.0)

**Comment by kin4stat** [comment]
И как теперь принудительно сменить тему?

**Comment by juvirez** [comment]
>И как теперь принудительно сменить тему?

@kin4stat убрать галку `Settings — Sync with OS theme` и выставлять нужную тему в настройках профиля яндекс музыки.

**Comment by kin4stat** [comment]
> >И как теперь принудительно сменить тему?
> 
> 
> 
> @kin4stat убрать галку `Settings — Sync with OS theme` и выставлять нужную тему в настройках профиля яндекс музыки.

Проблема в том, что меню настроек вообще не существует(описано в #204)

Поэтому собственно и спросил
