### ISSUE TITLE
Не работает на новой MacOS Sonoma

### ISSUE THREAD

**Issue by samtsevich** [juvirez/yandex-music-app#213]
Обновился до RC версии MacOS Sonoma (23A339), запускаю последнюю версию приложение (1.8.1) и само приложение выглядит как просто черный экран и ничего не происходит.

**Comment by vanokg** [comment]
Такая же проблема, только вот обновил я вчера, а проблема появилась буквально полчаса назад

**Comment by samtsevich** [comment]
Вау!
Само починилось, когда я переустановил приложение через brew и далее просто запустил его через терминал:
`open /Applications/Yandex\ Music\ Unofficial.app`

Вуаля!
Опять работает

**Comment by vanokg** [comment]
Без перестановки просто начало работать, видеть у Яндекса проблемы какие-то были
