### ISSUE TITLE
Uncatch Exception: A number was expected

### ISSUE THREAD

**Issue by juvirez** [juvirez/yandex-music-app#23]
Возникает при запуске. Воспроизводится только у одного пользователя.
![image (10)](https://user-images.githubusercontent.com/1862143/82367552-0c5b5100-9a25-11ea-88d6-bdcf9b0ff6ba.png)

**Comment by nightfurydev** [comment]
@juvirez - у меня тоже такое воспроизводилось на macOS 10.15.4 с версией плеера - 1.5.1. Обновился сегодня до macOS 10.15.5 и ошибка исчезла. Возможно помогла перезагрузка системы или же само обновление.

**Comment by rdscoo1** [comment]
Тоже выскакивала такая ошибка, но при следующем запуске не появилась. Также почему-то два запуска подряд не загружались никакие обложки, но на третий запуск заработало. Спасибо больше за приложение! Это просто находка!

**Comment by juvirez** [comment]
Починено в #29
Фикс в релизе [v1.6.0-alpha.1](https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.0-alpha.1)
