### ISSUE TITLE
Не открывается на Catalina 10.15.4

### ISSUE THREAD

**Issue by Heruvim6w** [juvirez/yandex-music-app#24]
Невозможно открыть приложение, так как нельзя проверить на наличие вредоносного ПО. Возможно это проблема не приложения, а просто я новичок в маках, но хотелось бы уточнить этот вопрос. Спасибо.
<img width="1068" alt="Снимок экрана 2020-05-25 в 19 35 06" src="https://user-images.githubusercontent.com/45229313/82830699-1ebf0a00-9ebf-11ea-9188-db9139ab9abf.png">

**Comment by juvirez** [comment]
Такое сообщение отображается при попытке открыть неподписанное приложение.
Моё приложение не подписано, потому что для этого нужен Apple Dev аккаунт, который стоит денег. Именно на него я и собираю донат.

Но приложение всё равно можно открыть. Нажимай "Показать в Finder", открой контекстное меню для app файла и выбирай "Открыть". При последующих запусках приложения такого сообщения не будет.

**Comment by Heruvim6w** [comment]
Огромное спасибо! Удачи вам в разработке)))
--
Отправлено из Mail.ru для Android понедельник, 25 мая 2020г., 20:19 +03:00 от Aleksandr Semyonov  notifications@github.com :
