### ISSUE TITLE
Feature request: переключение лайк\дизлайк хоткеем

### ISSUE THREAD

**Issue by suhotrub** [juvirez/yandex-music-app#25]
Привет, спасибо за программу! 
С помощью BTT вывел на тачбар кнопку лайка трека, которая дергает заданный хоткей, но этот же хоткей не работает в обратную сторону. Заводить два хоткея и две кнопки на тачбаре не очень удобно. Хотелось бы добавить возможность настройки хоткея который переключает текущее состояние лайк\дизлайк.
Спасибо

**Comment by juvirez** [comment]
Привет!
Спасибо за фидбек.
Добавлю в следующем релизе.

**Comment by juvirez** [comment]
готово: https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.0-alpha.1
