### ISSUE TITLE
Что играет

### ISSUE THREAD

**Issue by iswitch** [juvirez/yandex-music-app#26]
Добавьте возможность по хоткею в уведомлении посмотреть что сейчас играет. При смене трека не всегда это удобно.

**Comment by juvirez** [comment]
Отличная идея!

Сейчас для этих целей я использую виджет Now Playing для Notification Center.
Вот так он выглядит: https://take.ms/8HCqh
Свайп двумя пальцами — и видишь что играет.
Пока идея не реализована, рекомендую пользоваться им.

**Comment by juvirez** [comment]
В [последнем релизе](https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.0-alpha.1) добавил такую возможность.

**Comment by iswitch** [comment]
Добавьте в уведомление состояние лайка ♥️ и обложку трека. Что-бы было понятно, лайкал этот трек раньше или нет.

**Comment by juvirez** [comment]
>Добавьте в уведомление состояние лайка ♥️ и обложку трека.

Сделано в [1.6.0](https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.0)

**Comment by iswitch** [comment]
Ура! Спасибо!
