### ISSUE TITLE
Add `cmd+w` shortcut support

### ISSUE THREAD

**Issue by mvshmakov** [juvirez/yandex-music-app#28]
Привет, спасибо за проект!

Из-за того, что регистрируются кастомные шорткаты, становится невозможным использовать `cmd+w` на маке. Это довольно полезная фича, каждый раз скрывать окно через тачпад не очень удобно. Прошу поддержать данный функционал.

**Comment by juvirez** [comment]
@mvshmakov Привет!
Попробуй [последний релиз](https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.0-alpha.1).
В нём есть фикс.

**Comment by mvshmakov** [comment]
@juvirez работает как и хотелось, спасибо!
P.S. иконка в трее - очень хорошо :)
