### ISSUE TITLE
Обложка альбома в центре уведомлений

### ISSUE THREAD

**Issue by MoNTE48** [juvirez/yandex-music-app#30]
Привет, есть ли возможность подтягивать обложку альбома сюда?
![image](https://user-images.githubusercontent.com/6764600/83941827-bf31fa00-a7ee-11ea-8be2-e12a42f1b305.png)

**Comment by juvirez** [comment]
Привет! Возможность есть, попробую сделать.

**Comment by juvirez** [comment]
[released](https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.0)
