### ISSUE TITLE
Добавить возможность ограничения длины названия трека в трее

### ISSUE THREAD

**Issue by minya92** [juvirez/yandex-music-app#33]
Спасибо за приложение!
Мне очень понравилась идея с отображением текущего трека в трее, но хотелось бы иметь возможность его как-нибудь ограничить, потому что иногда попадаются длинные названия, которые занимают всю строку. 
Можно вынести в какую-нибудь настройку, можно по умолчанию поставить ограничение на кол-во символов.

**Comment by minya92** [comment]
![2020-06-24_16-18-04](https://user-images.githubusercontent.com/4252803/85565150-8f308680-b637-11ea-9740-6379db459863.png)

**Comment by juvirez** [comment]
[released](https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.0)
