### ISSUE TITLE
Добавить возможность посмотреть текст песни одной кнопкой 

### ISSUE THREAD

**Issue by SanCHEESE** [juvirez/yandex-music-app#35]
Предлагаю поместить ее на панели воспроизведения снизу, рядом с кнопкой HQ, а показывать справа, как сделано в детальной информации песни.

**Comment by juvirez** [comment]
Но и сейчас можно кликнуть на название трека — откроется детальная информация о песни, в том числе там будет и текст песни.

**Comment by SanCHEESE** [comment]
Да, пожалуй. Спасибо
