### ISSUE TITLE
Push-уведомление при нажатии play на touchbar

### ISSUE THREAD

**Issue by romanov0303** [juvirez/yandex-music-app#37]
При начале воспроизведения трека хотелось бы сразу видеть его название, то есть увидеть пуш с названием

**Comment by juvirez** [comment]
[released](https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.0)
Теперь если трек поставили на паузу больше 20 секунд назад, при нажатии на play появится уведомление.

**Comment by HansCraftsman** [comment]
Если трек стоит на паузе некоторое время (10-15 мин по ощущениям), то после нажатия кнопки Play, вылетает уведомление с названием трека, но трек не воспроизводится. Повторное нажатие Play запускает воспроизведение. Такое поведение ожидалось? 

Устройство: MBA M1
Версия на которой есть такой эффект - v1.6.0 и v1.6.1

**Comment by juvirez** [comment]
Это изменение тут не при чём. Тоже воспроизвожу эту проблему.
Почему-то после вызова Play, апи яндекс музыки переставляет статус в playing и сразу же в paused.
Буду разбираться тут: #107
