### ISSUE TITLE
Ошибка если нет обложки у плейлиста

### ISSUE THREAD

**Issue by dimon1985** [juvirez/yandex-music-app#39]
Выводится ошибка если нет обложки у плейлиста.
`Uncaught Exception:
TypeError: Cannot read property 'cover' of undefined
    at trackToMetaData (/Applications/Yandex Music (Unofficial).app/Contents/Resources/app.asar/src/main/features/mediaService.js:75:19)
    at IpcMain.<anonymous> (/Applications/Yandex Music (Unofficial).app/Contents/Resources/app.asar/src/main/features/mediaService.js:13:18)
    at IpcMain.emit (events.js:203:13)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3850:15)
    at WebContents.emit (events.js:203:13)`

![ice_screenshot_20200717-102443](https://user-images.githubusercontent.com/8317488/87760127-f9dc7880-c817-11ea-9db9-759063df2c4b.png)

**Comment by juvirez** [comment]
Это уже чинили в #27
Попробуй установить последнюю версию приложения: https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.0-alpha.1
Если продолжает воспроизводиться — скинь ссылку на песню без обложки. Я не смог найти трек без обложки :)

**Comment by dimon1985** [comment]
> Это уже чинили в #27
> Попробуй установить последнюю версию приложения: https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.0-alpha.1
> Если продолжает воспроизводиться — скинь ссылку на песню без обложки. Я не смог найти трек без обложки :)

В том то и дело что стоит - Version 1.6.0-alpha.1 (1.6.0-alpha.1)
![ice_screenshot_20200717-160411](https://user-images.githubusercontent.com/8317488/87789128-31164e00-c847-11ea-8367-caae8390ca62.png)

**Comment by juvirez** [comment]
>Ссылка на плейлист - https://music.yandex.ru/users/Veroncoolak/playlists/1036?token=274c31a5-eb6c-4d21-bf08-254fb080d9db

У меня тут пусто: https://take.ms/c2f1a

**Comment by dimon1985** [comment]
> https://music.yandex.ru/users/Veroncoolak/playlists/1036?token=274c31a5-eb6c-4d21-bf08-254fb080d9db
Походу яндекс не дает расшаривать, если треки залиты с компа.
Трэка там есть 
![Screenshot (3)](https://user-images.githubusercontent.com/8317488/87790427-396f8880-c849-11ea-8001-920d247ceadb.png)
Попробуйте свой создать и залить с компа и создать плейлист, увидите проблему.

**Comment by ptelevich** [comment]
Так бы хотелось поскорее новую версию с фиксом этого бага.
P.S. Значёк в трее прыгает, чуть-чуть раздражает :(

**Comment by juvirez** [comment]
[released](https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.0)
