### ISSUE TITLE
Скрыть иконку в доке

### ISSUE THREAD

**Issue by gener** [juvirez/yandex-music-app#42]
В 1.6 есть поддержка иконки в треке. Было бы здорово, если бы еще можно было убрать иконку из дока оставить только в трее

**Comment by vadim-hgg** [comment]
Поддерживаю. Очень классная реализация иконки в трее, а в доке место занимает. :) было бы классно иметь возможность скрыть и вернуть. но до скрытия надо добавить открытие окна программы по двойному клику на иконке в трее.

**Comment by juvirez** [comment]
Released: [v1.7.0](https://github.com/juvirez/yandex-music-app/releases/tag/v1.7.0)
