### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by fatalist** [juvirez/yandex-music-app#47]
**Version 1.6.0-alpha.1 (1.6.0-alpha.1)**

Порядка 60-65% CPU usage когда приложение на виду.
Кулеры работают на полную.
Вместе с тем, если его свернуть, то 30-35%.
Такое началось после обновления на указанную версию.

**Comment by AlexeyKot** [comment]
У меня на свежей Каталине нагрузка 0.2 0.3 процента, когда в фоне.

**Comment by SergiuSavva** [comment]
На моём Macbook Pro 15 2015, 4.6-0.5%  CPU на MacOS 10.15.7

**Comment by InFuz** [comment]
Не знаю связано или нет, но еще в то время когда я пользовался не этим приложением, а веб версией на своем Macbook Pro 15 (2018) наблюдал повышенную загрузку CPU в тот момент когда веб версия Яндекс музыки отображала анимацию воспроизводящегося трека (увеличиваешься/уменьшающийся желтый кружок). И именно эта анимация у меня загружала CPU весьма сильно.

![image](https://user-images.githubusercontent.com/16736825/115214012-29a40e00-a113-11eb-9619-ef62b5604e91.png)

**Comment by juvirez** [comment]
Ого! Спасибо за наводку. Поисследую это.
Если дело в этом — зарепортаю. А конкретно в приложении возможно смогу отключить скрипты, отвечающие за эту анимацию.

**Comment by InFuz** [comment]
Я сам писал в сапорт ЯМ еще в декабре 2019 года, они приняли к сведению, но по моему с того времени так ни чего и не сделали. А мне порекомендовали отключить через блокировщик рекламы собственно элемент который эту анимацию отображает с css классом d-track__bubble.
В итоге я в тот раз сделал немного по другому написал свое простенькое расширение для браузера который в веб версии отключал на уровне css эту анимацию, но не удалял сам элемент из DOM.

**Comment by InFuz** [comment]
Они еще вроде писали что знают о такой проблеме, но воспроизводится она мало у кого. Возможно наличие такой проблемы как то связано с тем, что я Macbook использую всегда с подключенным внешним монитором и поэтому у меня всегда активно GPU не интегрировано на CPU а дискретное радеоновское. Хотя хз связано ли это.

**Comment by sergeyklochko** [comment]
У меня суммарно процессы приложения едят около 25-30%. есть внешний монитор подключенный к iMac. возможно, что проблема действительно в этом.

**Comment by Slauta** [comment]
Нужно учитывать тот факт что приложение написано на electron, а это симбиоз chrome и nodejs. Само приложение не является приложение, а лишь браузером, открывающем страницу яндекс музыки внутри chrome.

Теперь касательно этой проблемы. Скорее всего она связана с тем что у вас проблема с железом и chrome внутри электрона использует gpu ускорение, чтобы все красиво работало.

Могу предложить попробовать отключить ускорение через префикс запуска приложения, есть большая вероятность что поможет.

Например как-то так
`Yandex Music (Unofficial).app --enable-transparent-visuals --disable-gpu`

У самого электрона есть issue на эту тему [https://github.com/electron/electron/issues/11908](https://github.com/electron/electron/issues/11908)

**Comment by ndrwbv-dodo** [comment]
У меня тоже подъедает CPU 

<img width="964" alt="image" src="https://user-images.githubusercontent.com/92292051/162184437-1e8e813a-3d8d-47ca-b5d0-8c4b7d929721.png">

**Comment by juvirez** [comment]
У кого-нибудь тут ещё остались проблема высокого потребления CPU?
Кажется, после [v1.6.3](https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.3) проблема ушла?
