### ISSUE TITLE
При открытии глобальных хоткеев ошибка

### ISSUE THREAD

**Issue by ILYA2606** [juvirez/yandex-music-app#48]
Настроены хоткеи: Лайк F5, Дизлайк F6. В итоге дизлайн работает, а лайк нет.  
И при повторном открытии глобальных хоткеев отображается алерт с ошибкой:
<img width="643" alt="image" src="https://user-images.githubusercontent.com/283493/95471355-85ceee00-098a-11eb-947a-5438a473b915.png">

**Comment by juvirez** [comment]
Настроил такие же хоткеи, но воспроизвести не смог.
Выглядит как будто покараптался файл с настройками.

Можно попробовать удалить файл `~/Library/Application\ Support/yandex-music-app/Settings`

**Comment by juvirez** [comment]
После релиза #91 алертов никаких больше не будет.
