### ISSUE TITLE
Отключить спящий режим

### ISSUE THREAD

**Issue by romant094** [juvirez/yandex-music-app#50]
Добрый день,
Крутое приложение, я очень доволен. Работает лучше, чем браузерное (управление через Control Strip и нет проблем при управлении через AirPods).
Но есть минус (конкретно для меня). Если играет музыка, то мак переходит в спящий режим. Это очень неудобно. Можно это поправить или добавить настройку, чтобы блокировать переход в спящий режим?
Есть консольная команда `pmset noidle`, поэтому не думаю, что это будет сложно.
Надеюсь на ответ и заранее спасибо :-)

**Comment by romant094** [comment]
Up!
Ребята. Прошло достаточно много времени уже. Сможете реализовать?

**Comment by juvirez** [comment]
Привет!
Пока не очень получается уделять время на этот проект.
Но идея хорошая, я постараюсь сделать релиз в этом месяце.

**Comment by romant094** [comment]
Будет супер круто! Спасибо!

**Comment by juvirez** [comment]
[released](https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.0)
