### ISSUE TITLE
Ставится на паузу сразу после старта воспроизведения

### ISSUE THREAD

**Issue by StipJey** [juvirez/yandex-music-app#52]
Иногда при нажатии на кнопку Play на клавиатуре музыка включается на секунду и останавливается. 

Если открыть окно, то будет отображаться сообщение: "Поставили на паузу, так как вы начали слушать музыку на другом устройстве". Это не соответствует действительности. Очевидно я бы не стал создавать эту ишью если бы и правда начинал слушать на другом устройстве.

Включить музыку получается лишь кликом по кнопке Play внутри программы. После этого управление с клавиатуры начинает работать корректно.

Пока однозначный способ воспроизведения я не нашел, но вероятно это происходит после выхода из спящего режима или долгого перерыва в прослушивании.

Спасибо за приложение, оно очень помогает и работает в целом очень хорошо!

**Comment by romant094** [comment]
Тоже наблюдаю иногда такую проблему. Не сильно напрягает, но если я не один, то ставлю плюс :-)

**Comment by juvirez** [comment]
Хм, ни разу такого не ловил.
Ноутбук получается без тачбара (с физическими функциональными клавишами)?

**Comment by dmitrybabich** [comment]
У меня тоже постоянно так происходит. MacBook Pro (16-inch, 2019) с тачбаром. И тоже не могу понять закономерность.  Почему-то яндекс.музыка думает что где-то еще играет музыка в другом месте.

**Comment by juvirez** [comment]
Помню такая проблема была в версии 1.5.0 и раньше. Но в 1.5.1 было пофикшено.
Вы используете последнюю версию приложения?
https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.0-alpha.1

Если да, используете ли вы глобальные горячие клавиши (выданы ли Accessibility Privacy)?
Если да, уйдёт ли проблема если отобрать у приложения эти права?

**Comment by alexby** [comment]
Та же проблема. 
Воспроизводится для меня легко - не работает всегда после прослушивания музыки на телефоне android с официального аппа (на телефоне включаю воспроизведение, останавливаю воспроизведение, закрываю апп).
Версия приложения 1.5.1, Accessibility Privacy не были выданы. Дал права, проверил - то же самое, отобрал - то же самое.

**Comment by shermike** [comment]
Такая же проблема на Windows 10. Возможно проблема в самом yandex.music, который не знает на каком именно устройстве воспроизводить музыку и выбирает последний используемый.

**Comment by juvirez** [comment]
Эта проблема была решена в [v1.6.2](https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.2)

**Comment by juvirez** [comment]
Теперь пауза возможна только если сама Яндекс Музыка посчитает, что где-то у этого аккаунта уже проигрывается музыка.
