### ISSUE TITLE
Ошибка при воспроизведении загруженных треков

### ISSUE THREAD

**Issue by yarvysee** [juvirez/yandex-music-app#55]
Версия: 1.6.0-alpha.1 (1.6.0-alpha.1)

<img width="324" alt="Снимок экрана 2020-12-17 в 22 02 46" src="https://user-images.githubusercontent.com/37342684/102519091-e037a980-40b3-11eb-84b0-4a743deb225a.png">

**Comment by juvirez** [comment]
Дубликат #39
Фикс будет в следующем релизе.
