### ISSUE TITLE
Добавить иконки ❤️ и 🚫 на TouchBar

### ISSUE THREAD

**Issue by serggl** [juvirez/yandex-music-app#56]
Сейчас есть только кнопки управления воспроизведением, чтобы нажать ❤️  🚫 приходится открывать приложение

**Comment by neonrostov** [comment]
@juvirez, сделал PR с таким функционалом https://github.com/juvirez/yandex-music-app/pull/67
Готов обсудить замечания по нему.

**Comment by juvirez** [comment]
>Для сабжа нужно вносить изменения electron-media-service

MacOS не поддерживает кнопки like/dislike в своём MediaService: https://developer.apple.com/documentation/mediaplayer/mpnowplayinginfocenter

**Comment by mityukov** [comment]
А нет возможности просто зарегистрировать глобальную shortkey, которая будет лайкать текущий трек?

Когда в режиме "Плейлист дня" или  "Моя волна" — очень полезно было бы (оно же подстраивается под статистику)

**Comment by HansCraftsman** [comment]
> А нет возможности просто зарегистрировать глобальную shortkey

Если есть свободная клавиша - то Settings -> Global Hotkeys и там забиндить эту клавишу. Я на MacBook Air m1 освободил клавиши f3, f4 и f5 с помощью программы Karabiner. Повесил на f5 - показ трека который сейчас играет.

**Comment by DanDolog** [comment]
Можно создать пресет на MTMR, я как раз хотел этим заняться, но приложение не поддерживает Apple Script

**Comment by juvirez** [comment]
https://github.com/juvirez/yandex-music-app/releases/tag/v1.7.0
