### ISSUE TITLE
Сохранение позиции и размера окна

### ISSUE THREAD

**Issue by perezvoni** [juvirez/yandex-music-app#57]
Здравствуйте, спасибо вам, замечательное приложение. Выручает

Пожалуйста, если это возможно, добавьте функцию запоминания размера окна для последующих включений программы при перезапуске.

спасибо, с наступающим НГ

**Comment by juvirez** [comment]
[released](https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.0)
