### ISSUE TITLE
Apple Silicon (M1)

### ISSUE THREAD

**Issue by vadimyer** [juvirez/yandex-music-app#58]
Реализуйте, пожалуйста, поддержку новых процессоров Apple.

**Comment by neronmoon** [comment]
Please do!

**Comment by ivan-gaydamakin** [comment]
+1

**Comment by SeRGei93** [comment]
да. очень ждем

**Comment by mkosterin** [comment]
+1

**Comment by landy2005** [comment]
Bump.

Может вы "зарелизите" 2ю альфу для всех?

**Comment by romant094** [comment]
> Есть какие-то проблемы с переходом на m1?

У меня не возникло. Был MacBook Pro 16'' на i9, сейчас на Apple M1 Pro. Разницы не заметил вообще.

**Comment by juvirez** [comment]
Нативная поддержка M1 в версии 1.6.0: https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.0

**Comment by juvirez** [comment]
Чтобы собрать приложение под M1 пришлось переименовать приложение (убрать скобки) из-за бага electron-userland/electron-builder#6562.
Поэтому, после установки придётся удалить вручную старую версию приложения.
