### ISSUE TITLE
Новая иконка для Big Sur

### ISSUE THREAD

**Issue by VillyVonka** [juvirez/yandex-music-app#60]
Например [эта от Ales Belski](https://onionicons.com/parse/files/macOSicons/60535963203ddf3f78e7f6362e1097ef_1605524032402_Yandex.Music.icns)

**Comment by slepoy1** [comment]
File not found.

**Comment by VillyVonka** [comment]
или от [Ivan Pashkov](https://t.me/ivpxs)

<img width="512" alt="f295293bfe7d7c2a3e42ad51854907aa_Yandex Music" src="https://user-images.githubusercontent.com/48676935/115161952-3be96200-a0a9-11eb-8972-c09245f9caf1.png">

**Comment by juvirez** [comment]
[released](https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.0)
