### ISSUE TITLE
Не удается авторизироваться с помощью сторонних сервисов (Google-аккаунта)

### ISSUE THREAD

**Issue by slepoy1** [juvirez/yandex-music-app#71]
Ранее Яндекс-аккаунт был создан с использованием Google-аккаунта.

При первой авторизации в приложении Yandex Music с помощью стороннего сервиса, а именно – входе через Google-аккаунт, в Safari открывается окно входа, но после выбора подходящего Google-аккаунта и ввода пароля, Safari предлагает закрыть окно авторизации, но в приложении Yandex Music вход по-прежнему не выполнен.

Авторизацию удалось выполнить только непосредственно через Яндекс-аккаунт.

Спасибо.

**Comment by juvirez** [comment]
https://github.com/juvirez/yandex-music-app/issues/163#issuecomment-1215743232
