### ISSUE TITLE
Apple: "Данное ПО необходимо обновить..."

### ISSUE THREAD

**Issue by slepoy1** [juvirez/yandex-music-app#72]
Установка приложения на MacOS Big Sur 11.2.3 (20D91) прошла успешно. Однако при первом запуске появляется сообщение с текстом:
```
Файл ***.app невозможно открыть, так как Apple не может проверить его на наличие вредоносного ПО.
Данное ПО необходимо обновить. Обратитесь к разработчику за подробной информацией.
```
![Image of Yaktocat](https://i.ibb.co/BC41Vvm/2021-04-18-22-06-58.png)

В настройках безопасности потребовалось разрешить запуск приложения.

**Comment by JustKing** [comment]
Это стандартное сообщение для приложений от неподтвержденных разработчиков если приложение скачано не через AppStore.

[Инструкция](https://support.apple.com/ru-ru/guide/mac-help/mchleab3a043/mac) с офф сайта apple, как открыть приложение при таком предупреждении

**Comment by juvirez** [comment]
[released](https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.0)

Это сообщение появляется при запуске приложений, которые не прошли нотаризацию у Apple.
Но чтобы её пройти, нужен платный Apple Dev Account. И именно на него я собирал донаты.

Спасибо всем, кто донатил. В последнем релизе приложение подписано и нотаризовано. Данного сообщения теперь не должно быть.
