### ISSUE TITLE
Скажите номер кошелька для благодарности!

### ISSUE THREAD

**Issue by vr-wonny** [juvirez/yandex-music-app#76]
Спасибо за приложение!
Думаю если вы в описании скинете номер кошелька куда скинуть благодарность, то будет меньше "issues" c текстом "Спасибо". Ну как минимум этого не было бы))

**Comment by juvirez** [comment]
@vr-wonny спасибо за отзыв :)
У репозитория есть кнопка Sponsor:
![image](https://user-images.githubusercontent.com/1862143/118853089-6f0b5500-b8e4-11eb-9ad7-19a62dcf46d2.png)
