### ISSUE TITLE
Social login still doesn't work

### ISSUE THREAD

**Issue by majorovms** [juvirez/yandex-music-app#8]
Nothing happens if click any of social buttons

![image](https://user-images.githubusercontent.com/49290534/63342637-097be480-c35d-11e9-9729-b1ecd64a1d0f.png)

**Comment by juvirez** [comment]
Я не воспроизвожу — все социальные кнопки должны быть скрыты. Сделать их рабочими довольно проблематично, но возможно в будущем сделаю.
