### ISSUE TITLE
Потрескивание музыки в начале трека на Big Sur 11.5.1 (20G80)

### ISSUE THREAD

**Issue by jkttim** [juvirez/yandex-music-app#84]
Спасибо огромное за труд и крутое приложение!
После обновления на Big Sur появились посторонние потрескивания при переключении на новый трек и при перемотке.
Спасибо.

**Comment by juvirez** [comment]
Это старая проблема MacOS и её вроде как уже исправили.
https://forums.macrumors.com/threads/macbook-pro-2018-speakers-crackling.2128234/

Попробуй обновить MacOS до последней версии.
