### ISSUE TITLE
Пропала кнопка назад

### ISSUE THREAD

**Issue by homm** [juvirez/yandex-music-app#89]
Раньше рядом со строкой поиска была кнопка назад, теперь поиск переместился в другое место, а кнопки нигде нет.

**Comment by slepoy1** [comment]
Очень не хватает кнопки "Назад". Спасибо.

**Comment by juvirez** [comment]
Кнопка назад вернулась в свежем релизе: https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.0
