### ISSUE TITLE
Огромное человеческое спасибо!

### ISSUE THREAD

**Issue by metiskot** [juvirez/yandex-music-app#93]
Отличное приложение. Огромное спасибо за проделанную работу и успехов в развитии!

**Comment by HansCraftsman** [comment]
Поддерживаю! Каждый день его использую, добавить бы возможность сохранять размер и положение окна после перезапуска и вообще было бы все четко! Спасибо

**Comment by PrisedRabbit** [comment]
Присоединяюсь! Спасибо!

**Comment by WntSumMo** [comment]
+1

**Comment by juvirez** [comment]
😊

>добавить бы возможность сохранять размер и положение окна после перезапуска 

Это сделано тут #57 и будет доступно в следующем релизе.
