### ISSUE TITLE
Скролл бар остаётся светлого цвета при включённой тёмной теме

### ISSUE THREAD

**Issue by rakleed** [juvirez/yandex-music-app#94]
Пожалуйста, при включённой тёмной теме сделайте скролл бар также тёмного цвета. Для воспроизведения проблемы в настройках macOS › Основные для «Показывать полосы прокрутки:» должен быть включён «Всегда» (у меня также воспроизводится с «Автоматически», что является опцией по умолчанию).

<details><summary>Скриншот</summary>

![image](https://user-images.githubusercontent.com/19418601/143679071-c15a4b67-5b8b-49e2-a4b3-cb47f906f764.png)

</details>

**Comment by vanokg** [comment]
У меня нормально, крайняя бета.
<img width="1680" alt="Screenshot 2021-11-27 at 20 54 18" src="https://user-images.githubusercontent.com/3435030/143686433-ca9c485f-6915-4c6a-ae41-a52268e3138a.png">

**Comment by rakleed** [comment]
@vanokg у меня установлена [v1.6.0-alpha.1](https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.0-alpha.1), а у вас какая?

**Comment by vanokg** [comment]
> @vanokg у меня установлена [v1.6.0-alpha.1](https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.0-alpha.1), а у вас какая?

Version 1.6.0-alpha.1 (1.6.0-alpha.1)

**Comment by rakleed** [comment]
Ну я попробовал поменять тему на светлую и обратно на тёмную в настройках Яндекс.Музыки, потом в macOS, а также переустановить приложение, но скролл бар всё равно остаётся светлым.

У меня macOS 12.0.1, Yandex Music (Unofficial) 1.6.0-alpha.1.

**Comment by rakleed** [comment]
@vanokg для воспроизведения проблемы в настройках macOS › Основные для «Показывать полосы прокрутки:» должен быть включён «Всегда» (у меня также воспроизводится с «Автоматически», что является опцией по умолчанию). А у вас по всей видимости выбран «При прокручивании».

@juvirez

**Comment by juvirez** [comment]
Воспроизвёл

**Comment by rakleed** [comment]
@juvirez смотрю ты довольно много улучшений сделал по сравнению с последней доступной версией. Планируешь ли сделать пререлизную версию в ближайшее время для теста изменений?

**Comment by juvirez** [comment]
@rakleed да, скоро будет

**Comment by juvirez** [comment]
Исправлено в [v1.8.0](https://github.com/juvirez/yandex-music-app/releases/tag/v1.8.0)
