### ISSUE TITLE
Идея. Добавить возможность вернуться на предыдущую страницу.

### ISSUE THREAD

**Issue by rusmux** [juvirez/yandex-music-app#96]
Невозможно вернуться на предыдущую страницу, что порой было бы очень кстати

**Comment by zzonderr** [comment]
На macOS для возврата на предыдущую страницу работает системное сочетание **CMD + [**. На Windows скорее всего тоже есть аналогичное сочетание.

**Comment by juvirez** [comment]
Duplicate of #89
