### ISSUE TITLE
Приложение переключает ноутбук на использование более производительной видеокарты

### ISSUE THREAD

**Issue by ivd** [juvirez/yandex-music-app#97]
За счет этого увеличивается расход батареи.

**Comment by romant094** [comment]
Вопрос не в приложении, а в самом сервисе. Если зайдете на сайте яндекс музыки через браузер, то будет то же самое. А дело все в анимации, которую они добавили на сайт.
Это приложение по сути браузер с одной доступной вкладкой, на которой прописан адрес музыки.

**Comment by Avol-V** [comment]
https://github.com/electron/electron/issues/9842

**Comment by ivd** [comment]
> Вопрос не в приложении, а в самом сервисе. Если зайдете на сайте яндекс музыки через браузер, то будет то же самое. А дело все в анимации, которую они добавили на сайт. Это приложение по сути браузер с одной доступной вкладкой, на которой прописан адрес музыки.

Это первое что я проверил, в том то и дело, что в том же хроме Яндекс музыка не переключает на дискретную видеокарту.

**Comment by romant094** [comment]
Интересно, потому что у меня переключало... :-)
Magic

**Comment by bierzorutas** [comment]
force_high_performance_gpu not working in windows, performance with webgl game is mega pooor

**Comment by juvirez** [comment]
Как вариант, можно сделать Power Save Mode, который будет вырезать элементы с анимацией.
Ну и можно автоматически переключать в него, когда ноут работает на батарейке.

**Comment by mbarashkov** [comment]
Насколько я понимаю это всё же должно работать на macOS (такой флаг), а это уже будет что-то. Очень прошу реализовать :)

**Comment by juvirez** [comment]
Тут у кого-нибудь осталась проблема?
После релиза [v1.6.3](https://github.com/juvirez/yandex-music-app/releases/tag/v1.6.3), в котором была убрана анимация "Моя волна", теперь должно быть ок.

**Comment by mbarashkov** [comment]
Вообще macOS всё так же переключает на discrete GPU :(
её использование упало с вырезанием моей волны. Но переключает при запуске приложения.
@juvirez
