### ISSUE TITLE
Поменять иконку, чтобы она соответствовала новому дизайну Mac os

### ISSUE THREAD

**Issue by uf0logic** [juvirez/yandex-music-app#99]
Вариант Иконки с сайта https://macosicons.com

[icon.icns.zip](https://github.com/juvirez/yandex-music-app/files/7798269/icon.icns.zip)

**Comment by niksok13** [comment]
Как раз сегодня рисовал иконку, ближе и к safari и к yandex music по стилю) (да, пережидаю релиза под m1 на unite) 
[AppIcon.icns.zip](https://github.com/juvirez/yandex-music-app/files/7873323/AppIcon.icns.zip)

**Comment by juvirez** [comment]
Исправлено в [v1.8.0](https://github.com/juvirez/yandex-music-app/releases/tag/v1.8.0)
